In [1]:
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
import streamlit as st
import psutil

from mainnet_launch.constants import AutopoolConstants

from mainnet_launch.database.schema.full import (
    AutopoolStates,
    Blocks,
    DestinationStates,
    Destinations,
    AutopoolDestinationStates,
    DestinationTokenValues,
    TokenValues
)
from mainnet_launch.database.schema.postgres_operations import (
    merge_tables_as_df,
    TableSelector,
)
from mainnet_launch.data_fetching.get_state_by_block import build_blocks_to_use


def fetch_nav_per_share(autopool: AutopoolConstants) -> pd.DataFrame:
    nav_per_share_df = merge_tables_as_df(
        [
            TableSelector(
                table=AutopoolStates,
                select_fields=AutopoolStates.nav_per_share,
                join_on=None,
                row_filter=(AutopoolStates.autopool_vault_address == autopool.autopool_eth_addr),
            ),
            TableSelector(
                table=Blocks,
                select_fields=Blocks.datetime,
                join_on=(AutopoolStates.chain_id == Blocks.chain_id) & (AutopoolStates.block == Blocks.block),
            ),
        ],
        where_clause=Blocks.block.in_(build_blocks_to_use(autopool.chain)),
        order_by=Blocks.datetime,
    )
    nav_per_share_df = nav_per_share_df.set_index("datetime")
    nav_per_share_df.columns = [autopool.name]

    nav_per_share_df["30_day_difference"] = nav_per_share_df[autopool.name].diff(periods=30)
    nav_per_share_df["30_day_annualized_return"] = (
        (nav_per_share_df["30_day_difference"] / nav_per_share_df[autopool.name].shift(30)) * (365 / 30) * 100
    )
    nav_per_share_df["7_day_difference"] = nav_per_share_df[autopool.name].diff(periods=7)
    nav_per_share_df["7_day_annualized_return"] = (
        (nav_per_share_df["7_day_difference"] / nav_per_share_df[autopool.name].shift(7)) * (365 / 7) * 100
    )
    nav_per_share_df["daily_return"] = nav_per_share_df[autopool.name].pct_change()
    nav_per_share_df["7_day_MA_return"] = nav_per_share_df["daily_return"].rolling(window=7).mean()
    nav_per_share_df["7_day_MA_annualized_return"] = nav_per_share_df["7_day_MA_return"] * 365 * 100
    nav_per_share_df["30_day_MA_return"] = nav_per_share_df["daily_return"].rolling(window=30).mean()
    nav_per_share_df["30_day_MA_annualized_return"] = nav_per_share_df["30_day_MA_return"] * 365 * 100
    return nav_per_share_df


def fetch_key_metrics_data(autopool: AutopoolConstants):
    nav_per_share_df = fetch_nav_per_share(autopool)

    destination_state_df = merge_tables_as_df(
        selectors=[
            TableSelector(
                DestinationStates,
                select_fields=[
                    DestinationStates.destination_vault_address,
                    DestinationStates.block,
                    DestinationStates.incentive_apr,
                    DestinationStates.fee_apr,
                    DestinationStates.base_apr,
                    DestinationStates.price_per_share,
                    DestinationStates.price_return,
                ],
            ),
            TableSelector(
                AutopoolDestinationStates,
                [
                    AutopoolDestinationStates.owned_shares,
                ],
                (DestinationStates.destination_vault_address == AutopoolDestinationStates.destination_vault_address)
                & (DestinationStates.chain_id == AutopoolDestinationStates.chain_id)
                & (DestinationStates.block == AutopoolDestinationStates.block),
            ),
            TableSelector(
                Destinations,
                [Destinations.pool_type, Destinations.underlying_symbol],
                (DestinationStates.destination_vault_address == Destinations.destination_vault_address)
                & (DestinationStates.chain_id == Destinations.chain_id),
            ),
            TableSelector(
                AutopoolStates,
                [AutopoolStates.total_nav],
                (AutopoolStates.autopool_vault_address == autopool.autopool_eth_addr)
                & (AutopoolStates.chain_id == DestinationStates.chain_id)
                & (AutopoolStates.block == DestinationStates.block),
            ),
            TableSelector(
                Blocks,
                Blocks.datetime,
                (DestinationStates.block == Blocks.block) & (DestinationStates.chain_id == Blocks.chain_id),
            ),
        ],
        where_clause=(AutopoolDestinationStates.autopool_vault_address == autopool.autopool_eth_addr)
        & (Blocks.block.in_(build_blocks_to_use(autopool.chain))),
        order_by=Blocks.datetime,
    )

    destination_state_df["unweighted_apr"] = destination_state_df[["fee_apr", "base_apr", "incentive_apr"]].sum(axis=1)


    owned_shares_df = destination_state_df.groupby(['datetime', 'underlying_symbol'])[['owned_shares']].sum().reset_index().pivot(
        index="datetime", values="owned_shares", columns="underlying_symbol"
    )
    
    # I expect max and min to be the same for each destiantion here, if they exist at all
    highest_value_by_destination_symbol = destination_state_df.groupby(['datetime', 'underlying_symbol'])[['price_per_share', 'unweighted_apr', 'price_return']].max().reset_index()
    price_per_share_df = highest_value_by_destination_symbol.pivot(
        index="datetime", values="price_per_share", columns="underlying_symbol"
    )

    price_return_df = highest_value_by_destination_symbol.pivot(
        index="datetime", values="price_return", columns="underlying_symbol"
    )

    allocation_df = (price_per_share_df * owned_shares_df).fillna(0)
    total_nav_series = allocation_df.sum(axis=1)

    portion_df = allocation_df.div(total_nav_series, axis=0)


    uwcr_df = highest_value_by_destination_symbol.pivot(index="datetime", values="unweighted_apr", columns="underlying_symbol")
    expected_return_series = 100 * (portion_df.fillna(0) * uwcr_df.fillna(0)).sum(axis=1)


    weighted_price_return_series = -100 * (portion_df.fillna(0) * price_return_df.fillna(0)).sum(axis=1)


    highest_block_and_datetime = destination_state_df[["block", "datetime"]].max()

    return (
        nav_per_share_df,
        total_nav_series,
        expected_return_series,
        allocation_df,
        weighted_price_return_series,
        highest_block_and_datetime,
        price_return_df,
        portion_df,
    )


from mainnet_launch.constants import AUTO_ETH, AUTO_USD
import plotly.io as pio

pio.templates.default = None

# (
#     nav_per_share_df,
#     total_nav_series,
#     expected_return_series,
#     allocation_df,
#     weighted_price_return_series,
#     highest_block_and_datetime,
#     price_return_df,
#     portion_df,
# ) = fetch_key_metrics_data(AUTO_USD)

# allocation_df

2025-05-07 14:07:21.674 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

In [ ]:
destination_state_df = merge_tables_as_df(
    selectors=[
        TableSelector(
            DestinationStates,
            select_fields=[
                DestinationStates.block,
                DestinationStates.price_per_share,
                DestinationStates.price_return,
                DestinationStates.underlying_token_total_supply,
            ],
        ),
        TableSelector(
            DestinationTokenValues,
            select_fields=[
                DestinationTokenValues.spot_price,
                DestinationTokenValues.quantity,
            ],
            join_on=(
                (DestinationStates.destination_vault_address == DestinationTokenValues.destination_vault_address)
                & (DestinationStates.chain_id              == DestinationTokenValues.chain_id)
                & (DestinationStates.block                 == DestinationTokenValues.block)
            )
        ),

        TableSelector(
            Destinations,
            select_fields=[
                Destinations.underlying_symbol,
                Destinations.pool_type,            
            ],
            join_on=(
                (Destinations.destination_vault_address == DestinationStates.destination_vault_address)
                & (Destinations.chain_id              == DestinationStates.chain_id)
            )
        ),
        TableSelector(
            AutopoolDestinationStates,
            select_fields=[AutopoolDestinationStates.owned_shares],
            join_on=(
                (DestinationStates.destination_vault_address == AutopoolDestinationStates.destination_vault_address)
                & (DestinationStates.chain_id              == AutopoolDestinationStates.chain_id)
                & (DestinationStates.block                 == AutopoolDestinationStates.block)
            ),
        ),
        TableSelector(
            TokenValues,
            select_fields=[TokenValues.safe_price, TokenValues.backing],
            join_on=(
                (DestinationTokenValues.token_address == TokenValues.token_address)
                & (DestinationTokenValues.chain_id    == TokenValues.chain_id)
                & (DestinationTokenValues.block       == TokenValues.block)
            )
        ),

        TableSelector(
            Blocks,
            select_fields=[Blocks.datetime],
            join_on=(
                (DestinationStates.chain_id == Blocks.chain_id)
                & (DestinationStates.block    == Blocks.block)
            ),
        ),
    ],
    where_clause=(
        (AutopoolDestinationStates.autopool_vault_address == AUTO_USD.autopool_eth_addr)
        & (Blocks.block.in_(build_blocks_to_use(AUTO_USD.chain)))
    ),
    order_by=Blocks.datetime,
)

destination_state_df

2025-05-07 14:13:26.298 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-07 14:13:26.299 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-07 14:13:26.299 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-07 14:13:26.299 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-07 14:13:26.300 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

2025-05-07 14:13:26,301 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-05-07 14:13:26,301 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-05-07 14:13:26,301 INFO sqlalchemy.engine.Engine [cached since 349.8s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x13c7063b0>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-05-07 14:13:26,302 INFO sqlalchemy.engine.Engine SELECT
    destination_states.block,
    destination_states.price_per_share,
    destination_states.price_return,
    destination_states.underlying_token_total_supply,
    destination_token_values.spot_price,
    destination_token_values.quantity,
    destinations.underlying_symbol,
    destinations.pool_type,
    autopool_destination_states.owned_shares,
    token_values.safe_price,
    token_values.backing,
    blocks.datetime
FROM destination_states
JOIN destination_token_values
  ON destination_states.destination_vault_address = destination_token_values.destination_vault_address AND destination_states.chain_id = destination_token_values.chain_id AND destination_states.block = destination_token_values.block
JOIN destinations
  ON destinations.destination_vault_address = destination_states.destination_vault_address AND destinations.chain_id = destination_states.chain_id
JOIN autopool_destination_states
  ON destination_states.destination_vault_address = autopool_destination_states.destination_vault_address AND destination_states.chain_id = autopool_destination_states.chain_id AND destination_states.block = autopool_destination_states.block
JOIN token_values
  ON destination_token_values.token_address = token_values.token_address AND destination_token_values.chain_id = token_values.chain_id AND destination_token_values.block = token_values.block
JOIN blocks
  ON destination_states.chain_id = blocks.chain_id AND destination_states.block = blocks.block
WHERE
    (autopool_destination_states.autopool_vault_address = '0xa7569A44f348d3D70d8ad5889e50F78E33d80D35' AND blocks.block IN (20759464, 20766617, 20773761, 20780916, 20788084, 20795238, 20802389, 20809562, 20816725, 20823901, 20831060, 20838231, 20845405, 20852572, 20859740, 20866918, 20874085, 20881261, 20888424, 20895606, 20902784, 20909955, 20917130, 20924302, 20931482, 20938657, 20945811, 20952957, 20960089, 20967244, 20974401, 20981560, 20988724, 20995892, 21003063, 21010230, 21017401, 21024558, 21031733, 21038905, 21046076, 21053236, 21060412, 21067570, 21074738, 21081894, 21089068, 21096238, 21103392, 21110559, 21117728, 21124888, 21132050, 21139209, 21146367, 21153541, 21160714, 21167883, 21175045, 21182212, 21189371, 21196531, 21203703, 21210874, 21218049, 21225225, 21232385, 21239548, 21246710, 21253879, 21261045, 21268202, 21275369, 21282522, 21289632, 21296777, 21303933, 21311105, 21318259, 21325415, 21332578, 21339732, 21346894, 21354047, 21361217, 21368389, 21375545, 21382702, 21389868, 21397030, 21404196, 21411356, 21418529, 21425699, 21432852, 21440009, 21447175, 21454314, 21461471, 21468617, 21475764, 21482924, 21490077, 21497235, 21504401, 21511571, 21518734, 21525890, 21533058, 21540232, 21547396, 21554556, 21561709, 21568863, 21576035, 21583203, 21590362, 21597520, 21604680, 21611852, 21619004, 21626161, 21633325, 21640491, 21647653, 21654814, 21661974, 21669146, 21676305, 21683471, 21690636, 21697804, 21704966, 21712129, 21719303, 21726465, 21733626, 21740792, 21747949, 21755110, 21762264, 21769421, 21776574, 21783739, 21790905, 21798074, 21805232, 21812397, 21819559, 21826720, 21833845, 21840991, 21848119, 21855250, 21862393, 21869537, 21876698, 21883855, 21890993, 21898155, 21905310, 21912465, 21919621, 21926782, 21933948, 21941120, 21948291, 21955462, 21962635, 21969800, 21976966, 21984128, 21991286, 21998438, 22005590, 22012750, 22019907, 22027064, 22034224, 22041393, 22048553, 22055722, 22062883, 22070044, 22077198, 22084356, 22091518, 22098694, 22105862, 22113034, 22120200, 22127350, 22134526, 22141688, 22148848, 22156001, 22163172, 22170334, 22177499, 22184669, 22191826, 22198999, 22206150, 22213305, 22220455, 22227624, 22234793, 22241970, 22249146, 22256323, 22263499, 22270667, 22277825, 22284996, 22292157, 22299326, 22306493, 22313650, 22320818, 22327989, 22335153, 22342307, 22349480, 22356658, 22363838, 22370998, 22378150, 22385293, 22392426, 22399543, 22406692, 22413825, 22420967, 22428091))
ORDER BY
    blocks.datetime ASC

2025-05-07 14:13:26,302 INFO sqlalchemy.engine.Engine [generated in 0.00033s] {}
2025-05-07 14:13:27,532 INFO sqlalchemy.engine.Engine ROLLBACK

,block,price_per_share,price_return,underlying_token_total_supply,spot_price,quantity,underlying_symbol,pool_type,owned_shares,safe_price,backing,datetime
0,20759464,NaN,NaN,NaN,NaN,NaN,SkySaver,curveNG,NaN,NaN,None,2024-09-15 23:59:59+00:00
1,20759464,NaN,NaN,NaN,NaN,NaN,crv2pool,curveNG,NaN,NaN,None,2024-09-15 23:59:59+00:00
2,20759464,NaN,NaN,NaN,NaN,NaN,crv2pool,curveNG,NaN,0.000431,None,2024-09-15 23:59:59+00:00
3,20759464,NaN,NaN,NaN,NaN,NaN,llamathena,curveNG,NaN,NaN,None,2024-09-15 23:59:59+00:00
4,20759464,NaN,NaN,NaN,NaN,NaN,llamathena,curveNG,NaN,NaN,None,2024-09-15 23:59:59+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
19183,22428091,NaN,NaN,2.557149e+09,0.000579,NaN,sUSDS,self,0.0,0.000579,None,2025-05-06 23:59:59+00:00
19184,22428091,NaN,NaN,4.419190e+08,0.000637,NaN,sDAI,self,0.0,0.000637,None,2025-05-06 23:59:59+00:00
19185,22428091,NaN,NaN,1.733134e+09,0.000645,NaN,sUSDe,self,0.0,0.000645,None,2025-05-06 23:59:59+00:00
19186,22428091,NaN,NaN,2.836610e-05,0.000551,3.182336e+07,waEthUSDT,aTokenStataV3,0.0,0.000551,None,2025-05-06 23:59:59+00:00
19187,22428091,NaN,NaN,2.891680e-05,0.000551,3.262039e+07,waEthUSDC,aTokenStataV3,0.0,0.000551,None,2025-05-06 23:59:59+00:00

In [ ]:
destination_state_df[destination_state_df['underlying_symbol'] =='autoUSD']

# the issue is that the safe price is in ETH and not in USD

,block,price_per_share,price_return,underlying_token_total_supply,spot_price,quantity,underlying_symbol,pool_type,owned_shares,safe_price,backing,datetime,portion_ownership,portion_of_quantity,safe_value,backing_value
52,20759464,1.0,0.0,NaN,1.0,NaN,autoUSD,idle,NaN,0.000431,None,2024-09-15 23:59:59+00:00,NaN,NaN,NaN,NaN
84,20766617,1.0,0.0,NaN,1.0,NaN,autoUSD,idle,NaN,0.000436,None,2024-09-16 23:59:59+00:00,NaN,NaN,NaN,NaN
245,20773761,1.0,0.0,NaN,1.0,NaN,autoUSD,idle,NaN,0.000426,None,2024-09-17 23:59:59+00:00,NaN,NaN,NaN,NaN
247,20780916,1.0,0.0,NaN,1.0,NaN,autoUSD,idle,NaN,0.000425,None,2024-09-18 23:59:59+00:00,NaN,NaN,NaN,NaN
404,20788084,1.0,0.0,NaN,1.0,NaN,autoUSD,idle,NaN,0.000403,None,2024-09-19 23:59:59+00:00,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18779,22399543,1.0,0.0,NaN,1.0,6.894454e-07,autoUSD,idle,6.894454e-07,0.000543,None,2025-05-02 23:59:59+00:00,NaN,NaN,NaN,NaN
18872,22406692,1.0,0.0,NaN,1.0,1.499124e-10,autoUSD,idle,1.499124e-10,0.000543,None,2025-05-03 23:59:59+00:00,NaN,NaN,NaN,NaN
19022,22413825,1.0,0.0,NaN,1.0,4.103062e-09,autoUSD,idle,4.103062e-09,0.000554,None,2025-05-04 23:59:59+00:00,NaN,NaN,NaN,NaN
19105,22420967,1.0,0.0,NaN,1.0,1.000164e-11,autoUSD,idle,1.000164e-11,0.000549,None,2025-05-05 23:59:59+00:00,NaN,NaN,NaN,NaN
19154,22428091,1.0,0.0,NaN,1.0,2.673834e-12,autoUSD,idle,2.673834e-12,0.000551,None,2025-05-06 23:59:59+00:00,NaN,NaN,NaN,NaN

In [ ]:
dest

In [15]:
destination_state_df['portion_ownership'] = destination_state_df['owned_shares'] / destination_state_df['underlying_token_total_supply']
destination_state_df['portion_of_quantity'] = destination_state_df['quantity'] * destination_state_df['portion_ownership']

destination_state_df['safe_value'] = destination_state_df['portion_of_quantity'] * destination_state_df['safe_price']
destination_state_df['backing_value'] = destination_state_df['portion_of_quantity'] * destination_state_df['backing']


safe_value_by_destination = destination_state_df.groupby(['datetime', 'underlying_symbol'])[['safe_value', 'backing_value']].sum().reset_index().pivot(
    index="datetime", values="safe_value", columns="underlying_symbol"
).fillna(0)

spot_value_by_destination = destination_state_df.groupby(['datetime', 'underlying_symbol'])[['spot_price', 'backing_value']].sum().reset_index().pivot(
    index="datetime", values="spot_price", columns="underlying_symbol"
).fillna(0)


px.bar(safe_value_by_destination)