In [2]:
import pandas as pd
from multicall import Call
import numpy as np
from web3 import Web3


from mainnet_launch.database.schema.full import (
    DestinationTokenValues,
    TokenValues,
    Autopools,
    DestinationStates,
    DestinationTokens,
    Destinations,
    AutopoolDestinationStates,
    Tokens,
    AutopoolStates,
)
import plotly.express as px


from mainnet_launch.abis import STATS_CALCULATOR_REGISTRY_ABI
from mainnet_launch.data_fetching.get_events import fetch_events


from mainnet_launch.database.schema.postgres_operations import (
    get_full_table_as_orm,
    get_full_table_as_df,
    insert_avoid_conflicts,
    get_subset_not_already_in_column,
    natural_left_right_using_where,
)
from mainnet_launch.data_fetching.get_state_by_block import (
    get_raw_state_by_blocks,
    safe_normalize_with_bool_success,
    build_blocks_to_use,
    identity_with_bool_success,
    get_state_by_one_block,
)
from mainnet_launch.constants import (
    ALL_CHAINS,
    ROOT_PRICE_ORACLE,
    ChainData,
)

from mainnet_launch.pages.autopool_diagnostics.lens_contract import (
    fetch_pools_and_destinations_df,
)


def build_autopool_state_calls(autopools: list[Autopools]) -> list[Call]:

    # autopool total Shaes
    # total_shares: Mapped[float] = mapped_column(nullable=False)  # vault.totalSupply
    # total_nav: Mapped[float] = m_column(nullable=False)  # nav
    # nav_per_share: Mapped[float] = mappedapped_column(nullable=False)  # nav per share

    name_calls = [
        Call(
            t,
            "name()(string)",
            [(t + "_name", identity_with_bool_success)],
        )
        for t in autopool_vault_addresses
    ]


def ensure_autopool_states_is_current():
    for chain in ALL_CHAINS:
        possible_blocks = build_blocks_to_use(chain)

        missing_blocks = get_subset_not_already_in_column(
            AutopoolDestinationStates,
            AutopoolDestinationStates.block,
            possible_blocks,
            where_clause=AutopoolDestinationStates.chain_id == chain.chain_id,
        )

        if len(missing_blocks) == 0:
            continue

In [4]:
wide_autopool_destination_df = natural_left_right_using_where(
    AutopoolDestinationStates,
    DestinationStates,
    using=[
        AutopoolDestinationStates.chain_id,
        AutopoolDestinationStates.block,
        AutopoolDestinationStates.destination_vault_address,
    ],
)

wide_autopool_destination_df

2025-04-27 16:54:53,810 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2025-04-27 16:54:53,811 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-04-27 16:54:54,008 INFO sqlalchemy.engine.Engine select current_schema()
2025-04-27 16:54:54,008 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-04-27 16:54:54,201 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2025-04-27 16:54:54,202 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-04-27 16:54:54,393 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-04-27 16:54:54,393 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-04-27 16:54:54,394 INFO sqlalchemy.engine.Engine [generated in 0.00087s] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x11cb6c340>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-04-27 16:54:54,394 INFO sqlalchemy.engine.Engine
            SELECT *
            FROM autopool_destination_states
            JOIN destination_states
            USING (chain_id, block, destination_vault_address)


2025-04-27 16:54:54,395 INFO sqlalchemy.engine.Engine [generated in 0.00063s] {}
2025-04-27 16:54:55,805 INFO sqlalchemy.engine.Engine ROLLBACK

,chain_id,block,destination_vault_address,autopool_vault_address,amount,total_safe_value,total_spot_value,total_backing_value,percent_ownership,incentive_apr,...,underlying_token_total_supply,safe_total_supply,price_per_share,price_return,underlying_safe_price,underlying_spot_price,underlying_backing,safe_backing_discount,spot_backing_discount,safe_spot_spread
0,1,20759464,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,0.000000,0.000000,0.000000,0.000000,0.000000,0.041235,...,13157.451200,12302.611124,1.036523,-0.000645,1.036523,1.036516,1.035855,0.000645,0.000638,0.000007
1,1,20759464,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,0x6dC3ce9C57b20131347FDc9089D740DAf6eB34c5,0.000000,0.000000,0.000000,0.000000,0.000000,0.041235,...,13157.451200,12302.611124,1.036523,-0.000645,1.036523,1.036516,1.035855,0.000645,0.000638,0.000007
2,1,20766617,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,0.000000,0.000000,0.000000,0.000000,0.000000,0.040938,...,13157.496413,12383.288934,1.036163,-0.000278,1.036163,1.036121,1.035875,0.000278,0.000237,0.000041
3,1,20766617,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,0x6dC3ce9C57b20131347FDc9089D740DAf6eB34c5,0.000000,0.000000,0.000000,0.000000,0.000000,0.040938,...,13157.496413,12383.288934,1.036163,-0.000278,1.036163,1.036121,1.035875,0.000278,0.000237,0.000041
4,1,20773761,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,0.000000,0.000000,0.000000,0.000000,0.000000,0.040507,...,13157.496413,12383.288934,1.036462,-0.000538,1.036462,1.036456,1.035906,0.000537,0.000531,0.000006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15707,8453,29288526,0xBd137c56f3116E5c36753037a784FF844F84F59c,0xAADf01DD90aE0A6Bb9Eb908294658037096E0404,436.556039,445.295904,445.265308,446.101317,94.757568,0.000000,...,460.708361,122.008900,1.020020,0.000000,1.020020,1.019950,1.021865,-0.001805,-0.001874,0.000069
15708,8453,29331726,0xBd137c56f3116E5c36753037a784FF844F84F59c,0xAADf01DD90aE0A6Bb9Eb908294658037096E0404,360.122746,367.381578,367.380513,368.025999,93.714426,0.000000,...,384.276746,122.008900,1.020157,0.000000,1.020157,1.020154,1.021946,-0.001751,-0.001754,0.000003
15709,8453,29374926,0xBd137c56f3116E5c36753037a784FF844F84F59c,0xAADf01DD90aE0A6Bb9Eb908294658037096E0404,275.206348,280.769753,280.773322,281.307250,91.930984,0.000000,...,299.361909,122.008900,1.020215,0.000000,1.020215,1.020228,1.022168,-0.001911,-0.001898,-0.000013
15710,8453,29418126,0xBd137c56f3116E5c36753037a784FF844F84F59c,0xAADf01DD90aE0A6Bb9Eb908294658037096E0404,158.711862,161.945294,161.942959,162.226681,86.790248,0.000000,...,182.868313,122.008900,1.020373,0.000000,1.020373,1.020358,1.022146,-0.001735,-0.001749,0.000014
15711,8453,29461326,0xBd137c56f3116E5c36753037a784FF844F84F59c,0xAADf01DD90aE0A6Bb9Eb908294658037096E0404,89.275423,91.067658,91.067939,91.261196,78.703638,0.000000,...,113.432396,122.008900,1.020075,0.000000,1.020075,1.020079,1.022243,-0.002121,-0.002118,-0.000003

In [5]:
wide_autopool_destination_df.columns

Index(['chain_id', 'block', 'destination_vault_address',
       'autopool_vault_address', 'amount', 'total_safe_value',
       'total_spot_value', 'total_backing_value', 'percent_ownership',
       'incentive_apr', 'fee_apr', 'base_apr', 'points_apr',
       'fee_plus_base_apr', 'total_apr_in', 'total_apr_out',
       'underlying_token_total_supply', 'safe_total_supply', 'price_per_share',
       'price_return', 'underlying_safe_price', 'underlying_spot_price',
       'underlying_backing', 'safe_backing_discount', 'spot_backing_discount',
       'safe_spot_spread'],
      dtype='object')

In [ ]:
autopool_total_destination_safe_value_by_block = (
    wide_autopool_destination_df.groupby(["autopool_vault_address", "block"])["total_safe_value"].sum().reset_index()
)
autopool_total_destination_safe_value_by_block.columns = [
    "autopool_vault_address",
    "block",
    "autopool_total_safe_value",
]

                          autopool_vault_address     block  total_safe_value
0     0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56  20759464          0.000000
1     0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56  20766617          0.000000
2     0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56  20773761         99.989238
3     0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56  20780916        560.414095
4     0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56  20788084       1429.848335
...                                          ...       ...               ...
1067  0xE800e3760FC20aA98c5df6A9816147f190455AF3  22327989        491.964071
1068  0xE800e3760FC20aA98c5df6A9816147f190455AF3  22335153        492.076268
1069  0xE800e3760FC20aA98c5df6A9816147f190455AF3  22342307        491.988405
1070  0xE800e3760FC20aA98c5df6A9816147f190455AF3  22349480        492.079276
1071  0xE800e3760FC20aA98c5df6A9816147f190455AF3  22356658        492.065171

[1072 rows x 3 columns]

In [2]:
limited_destination_states_df = destination_states_df[
    [
        "destination_vault_address",
        "block",
        "underlying_token_total_supply",
        "underlying_safe_price",
        "underlying_spot_price",
        "underlying_backing",
        "chain_id",
    ]
].copy()
autopool_destination_balance_of_df

,block,autopool_vault_address,destination_vault_address,balance_of
0,20759464.0,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,0.000000
1,20759464.0,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,0x865e59D439BF7310c9BC6117E6020B8C87De4065,0.000000
2,20759464.0,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,0x25cb41919d6B88e0D48108A4F5fe8FBb3744aFE1,0.000000
3,20759464.0,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,0x6DcB6797b1C0442587c2ad79745ef7BB487Fc2E2,0.000000
4,20759464.0,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,0xe3AE2Ab9AE8ADe1B4940dd893C9339401bEe61A1,0.000000
...,...,...,...,...
15003,22356658.0,0xE800e3760FC20aA98c5df6A9816147f190455AF3,0x60339056EC88996e41757E05a798310E46972cca,0.000000
15004,22356658.0,0xE800e3760FC20aA98c5df6A9816147f190455AF3,0x5c6aeb9ef0d5BbA4E6691f381003503FD0D45126,470.519208
15005,22356658.0,0x35911af1B570E26f668905595dEd133D01CD3E5a,0xc4Eb861e7b66f593482a3D7E8adc314f6eEDA30B,317.661117
15006,22356658.0,0x35911af1B570E26f668905595dEd133D01CD3E5a,0xe4433D00Cf48BFE0C672d9949F2cd2c008bffC04,0.000000
15007,22356658.0,0x35911af1B570E26f668905595dEd133D01CD3E5a,0xbA1462f43c6f60ebD1C62735c94E428aD073E01A,523.014004