In [4]:
import pandas as pd
from multicall import Call
import numpy as np
from web3 import Web3


from mainnet_launch.database.schema.full import (
    DestinationTokenValues,
    TokenValues,
    Autopools,
    DestinationStates,
    DestinationTokens,
    Destinations,
    AutopoolDestinationStates,
    Tokens,
    AutopoolStates,
)
import plotly.express as px


from mainnet_launch.abis import STATS_CALCULATOR_REGISTRY_ABI
from mainnet_launch.data_fetching.get_events import fetch_events


from mainnet_launch.database.schema.postgres_operations import (
    get_full_table_as_orm,
    get_full_table_as_df,
    insert_avoid_conflicts,
    get_subset_not_already_in_column,
    natural_left_right_using_where,
)
from mainnet_launch.data_fetching.get_state_by_block import (
    get_raw_state_by_blocks,
    safe_normalize_with_bool_success,
    build_blocks_to_use,
    identity_with_bool_success,
    get_state_by_one_block,
)
from mainnet_launch.constants import (
    ALL_CHAINS,
    ROOT_PRICE_ORACLE,
    ChainData,
)

from mainnet_launch.pages.autopool_diagnostics.lens_contract import (
    fetch_pools_and_destinations_df,
)


def _fetch_autopool_state_df(autopools: list[Autopools], missing_blocks: list[int], chain: ChainData) -> pd.DataFrame:

    def _extract_debt_plus_idle(success, AssetBreakdown):
        if success:
            totalIdle, totalDebt, totalDebtMin, totalDebtMax = AssetBreakdown
            return int(totalIdle + totalDebt) / 1e18
        return None

    calls = []
    for autopool in autopools:
        calls.extend(
            [
                Call(
                    autopool.autopool_vault_address,
                    ["totalSupply()(uint256)"],
                    [((autopool.autopool_vault_address, "total_shares"), safe_normalize_with_bool_success)],
                ),
                Call(
                    autopool.autopool_vault_address,
                    ["getAssetBreakdown()((uint256,uint256,uint256,uint256))"],
                    [((autopool.autopool_vault_address, "total_nav"), _extract_debt_plus_idle)],
                ),
                Call(
                    autopool.autopool_vault_address,
                    ["convertToAssets(uint256)(uint256)", int(1e18)],
                    [((autopool.autopool_vault_address, "nav_per_share"), safe_normalize_with_bool_success)],
                ),
            ]
        )

    autopool_state_df = get_raw_state_by_blocks(calls, missing_blocks, chain, include_block_number=True)
    return autopool_state_df


def _extract_autopool_state_rows(autopool_state_df: pd.DataFrame):

    new_autopool_states = []


def ensure_autopool_states_is_current():
    for chain in ALL_CHAINS:
        possible_blocks = build_blocks_to_use(chain)

        missing_blocks = get_subset_not_already_in_column(
            AutopoolStates,
            AutopoolStates.block,
            possible_blocks,
            where_clause=AutopoolStates.chain_id == chain.chain_id,
        )

        if len(missing_blocks) == 0:
            continue

        autopools = get_full_table_as_orm(Autopools, where_clause=Autopools.chain_id == chain.chain_id)

        autopool_state_df = _fetch_autopool_state_df(autopools, missing_blocks, chain)
        return autopool_state_df


autopool_state_df = ensure_autopool_states_is_current()
autopool_state_df

2025-04-27 20:07:38,507 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-04-27 20:07:38,513 INFO sqlalchemy.engine.Engine SELECT max(blocks.block) AS block
FROM blocks
WHERE blocks.chain_id = %(chain_id_1)s AND blocks.block >= %(block_1)s AND blocks.block <= %(block_2)s GROUP BY date_trunc(%(date_trunc_1)s, blocks.datetime) ORDER BY date_trunc(%(date_trunc_2)s, blocks.datetime)
2025-04-27 20:07:38,513 INFO sqlalchemy.engine.Engine [generated in 0.00053s] {'chain_id_1': 1, 'block_1': 20752910, 'block_2': 100000000, 'date_trunc_1': 'day', 'date_trunc_2': 'day'}
2025-04-27 20:07:38,751 INFO sqlalchemy.engine.Engine COMMIT
2025-04-27 20:07:38,841 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-04-27 20:07:38,842 INFO sqlalchemy.engine.Engine
            SELECT *
            FROM autopool_states
            WHERE autopool_states.chain_id = 1

2025-04-27 20:07:38,842 INFO sqlalchemy.engine.Engine [generated in 0.00043s] {}
2025-04-27 20:07:39,031 INFO sqlalchemy.engine.Engine COMMIT
2025-04-27 20:07:39,121 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-04-27 20:07:39,122 INFO sqlalchemy.engine.Engine
            SELECT *
            FROM autopools
            WHERE autopools.chain_id = 1

2025-04-27 20:07:39,123 INFO sqlalchemy.engine.Engine [generated in 0.00059s] {}
2025-04-27 20:07:39,310 INFO sqlalchemy.engine.Engine COMMIT

,"(0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56, total_shares)","(0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56, total_nav)","(0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56, nav_per_share)","(0x6dC3ce9C57b20131347FDc9089D740DAf6eB34c5, total_shares)","(0x6dC3ce9C57b20131347FDc9089D740DAf6eB34c5, total_nav)","(0x6dC3ce9C57b20131347FDc9089D740DAf6eB34c5, nav_per_share)","(0xE800e3760FC20aA98c5df6A9816147f190455AF3, total_shares)","(0xE800e3760FC20aA98c5df6A9816147f190455AF3, total_nav)","(0xE800e3760FC20aA98c5df6A9816147f190455AF3, nav_per_share)","(0x35911af1B570E26f668905595dEd133D01CD3E5a, total_shares)","(0x35911af1B570E26f668905595dEd133D01CD3E5a, total_nav)","(0x35911af1B570E26f668905595dEd133D01CD3E5a, nav_per_share)",block
timestamp,,,,,,,,,,,,,
2024-09-15 23:59:59+00:00,0.239949,0.239949,1.000000,1.000000e-13,1.000000e-13,1.000000,0.449884,0.449884,1.000000,NaN,NaN,NaN,20759464
2024-09-16 23:59:59+00:00,944.081116,944.081116,1.000000,6.109170e+02,6.107142e+02,0.999668,398.277626,398.277626,1.000000,NaN,NaN,NaN,20766617
2024-09-17 23:59:59+00:00,1654.392363,1654.384535,0.999995,1.025542e+03,1.024945e+03,0.999418,641.320724,641.244644,0.999881,NaN,NaN,NaN,20773761
2024-09-18 23:59:59+00:00,3133.620123,3133.327068,0.999906,1.817276e+03,1.815990e+03,0.999293,1149.219706,1148.786322,0.999623,NaN,NaN,NaN,20780916
2024-09-19 23:59:59+00:00,3903.814760,3901.645343,0.999444,1.947166e+03,1.945543e+03,0.999166,1389.852544,1389.059253,0.999429,NaN,NaN,NaN,20788084
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-04-23 23:59:59+00:00,13320.745844,13784.771713,1.034835,1.081396e+03,1.117050e+03,1.032970,478.869466,494.136743,1.031882,849.224032,860.944075,1.013801,22335153
2025-04-24 23:59:59+00:00,13340.566677,13806.582560,1.034932,1.078953e+03,1.114605e+03,1.033043,478.874032,494.267685,1.032146,849.244736,861.046513,1.013897,22342307
2025-04-25 23:59:59+00:00,14054.739402,14546.090669,1.034960,1.044624e+03,1.079424e+03,1.033313,478.871718,494.262104,1.032139,831.800530,843.439884,1.013993,22349480
2025-04-26 23:59:59+00:00,14029.470355,14521.845807,1.035096,1.044454e+03,1.079488e+03,1.033543,478.878421,494.403562,1.032420,832.003494,843.708763,1.014069,22356658
2025-04-27 23:59:59+00:00,14023.656780,14520.384977,1.035421,1.031509e+03,1.066242e+03,1.033672,478.877992,494.443413,1.032504,832.051372,844.011921,1.014375,22363838

In [3]:
wide_autopool_destination_df = natural_left_right_using_where(
    AutopoolDestinationStates,
    DestinationStates,
    using=[
        AutopoolDestinationStates.chain_id,
        AutopoolDestinationStates.block,
        AutopoolDestinationStates.destination_vault_address,
    ],
)

wide_autopool_destination_df

2025-04-27 20:06:40,302 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2025-04-27 20:06:40,303 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-04-27 20:06:40,490 INFO sqlalchemy.engine.Engine select current_schema()
2025-04-27 20:06:40,491 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-04-27 20:06:40,677 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2025-04-27 20:06:40,678 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-04-27 20:06:40,866 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-04-27 20:06:40,867 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-04-27 20:06:40,868 INFO sqlalchemy.engine.Engine [generated in 0.00156s] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x11d4c5de0>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-04-27 20:06:40,868 INFO sqlalchemy.engine.Engine
            SELECT *
            FROM autopool_destination_states
            JOIN destination_states
            USING (chain_id, block, destination_vault_address)


2025-04-27 20:06:40,869 INFO sqlalchemy.engine.Engine [generated in 0.00051s] {}
2025-04-27 20:06:42,197 INFO sqlalchemy.engine.Engine ROLLBACK

,chain_id,block,destination_vault_address,autopool_vault_address,amount,total_safe_value,total_spot_value,total_backing_value,percent_ownership,incentive_apr,...,underlying_token_total_supply,safe_total_supply,price_per_share,price_return,underlying_safe_price,underlying_spot_price,underlying_backing,safe_backing_discount,spot_backing_discount,safe_spot_spread
0,1,20759464,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,0.000000,0.000000,0.000000,0.000000,0.0,0.041235,...,13157.451200,12302.611124,1.036523,-0.000645,1.036523,1.036516,1.035855,0.000645,0.000638,0.000007
1,1,20759464,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,0x6dC3ce9C57b20131347FDc9089D740DAf6eB34c5,0.000000,0.000000,0.000000,0.000000,0.0,0.041235,...,13157.451200,12302.611124,1.036523,-0.000645,1.036523,1.036516,1.035855,0.000645,0.000638,0.000007
2,1,20766617,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,0.000000,0.000000,0.000000,0.000000,0.0,0.040938,...,13157.496413,12383.288934,1.036163,-0.000278,1.036163,1.036121,1.035875,0.000278,0.000237,0.000041
3,1,20766617,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,0x6dC3ce9C57b20131347FDc9089D740DAf6eB34c5,0.000000,0.000000,0.000000,0.000000,0.0,0.040938,...,13157.496413,12383.288934,1.036163,-0.000278,1.036163,1.036121,1.035875,0.000278,0.000237,0.000041
4,1,20773761,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,0.000000,0.000000,0.000000,0.000000,0.0,0.040507,...,13157.496413,12383.288934,1.036462,-0.000538,1.036462,1.036456,1.035906,0.000537,0.000531,0.000006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16855,8453,29331726,0xAADf01DD90aE0A6Bb9Eb908294658037096E0404,0xAADf01DD90aE0A6Bb9Eb908294658037096E0404,0.648453,0.648453,0.648453,0.648453,100.0,NaN,...,NaN,NaN,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
16856,8453,29374926,0xAADf01DD90aE0A6Bb9Eb908294658037096E0404,0xAADf01DD90aE0A6Bb9Eb908294658037096E0404,0.751798,0.751798,0.751798,0.751798,100.0,NaN,...,NaN,NaN,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
16857,8453,29418126,0xAADf01DD90aE0A6Bb9Eb908294658037096E0404,0xAADf01DD90aE0A6Bb9Eb908294658037096E0404,0.752076,0.752076,0.752076,0.752076,100.0,NaN,...,NaN,NaN,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
16858,8453,29461326,0xAADf01DD90aE0A6Bb9Eb908294658037096E0404,0xAADf01DD90aE0A6Bb9Eb908294658037096E0404,0.752076,0.752076,0.752076,0.752076,100.0,NaN,...,NaN,NaN,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
16859,8453,29504526,0xAADf01DD90aE0A6Bb9Eb908294658037096E0404,0xAADf01DD90aE0A6Bb9Eb908294658037096E0404,0.752076,0.752076,0.752076,0.752076,100.0,NaN,...,NaN,NaN,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000

In [ ]:
down_weighted_apr_values = []


# this so that we can sum up the values
def _extract_down_weighted_apr_values(row: dict) -> None:
    autopool_total_nav = row[(row["autopool_vault_address"], "total_nav")]
    this_destination_safe_value = row["total_safe_value"]
    portion_of_value_in_destination = this_destination_safe_value / autopool_total_nav

    downscaled_total_apr_out = row.get("total_apr_out", 0) * portion_of_value_in_destination
    downscaled_total_apr_in = row.get("total_apr_in", 0) * portion_of_value_in_destination
    downscaled_safe_backing_discount = row.get("total_apr_in", 0) * portion_of_value_in_destination

    down_weighted_apr_values.append(
        {
            "downscaled_total_apr_out": downscaled_total_apr_out,
            "downscaled_total_apr_in": downscaled_total_apr_in,
            "downscaled_safe_backing_discount": downscaled_safe_backing_discount,
            "autopool_vault_address": row["autopool_vault_address"],
            "block": row["block"],
        }
    )


# not certain what this is
very_wide_df.apply(_extract_down_weighted_apr_values, axis=1)

down_weighted_apr_df = pd.DataFrame.from_records(down_weighted_apr_values)
weighted_average_df = down_weighted_apr_df.groupby(["autopool_vault_address", "block"]).sum()
weighted_average_df.columns = [
    "weighted_average_total_apr_out",
    "weighted_average_total_apr_in",
    "weighted_average_safe_backing_discount",
]
weighted_average_df = weighted_average_df.reset_index()

weighted_average_df

,autopool_vault_address,block,weighted_average_total_apr_out,weighted_average_total_apr_in,weighted_average_safe_backing_discount
0,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,20759464,0.000000,0.000000,0.000000
1,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,20766617,0.000000,0.000000,0.000000
2,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,20773761,0.006059,0.006024,0.006024
3,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,20780916,0.016019,0.015922,0.015922
4,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,20788084,0.033280,0.033024,0.033024
...,...,...,...,...,...
895,0xE800e3760FC20aA98c5df6A9816147f190455AF3,22335153,0.084246,0.083994,0.083994
896,0xE800e3760FC20aA98c5df6A9816147f190455AF3,22342307,0.084246,0.083810,0.083810
897,0xE800e3760FC20aA98c5df6A9816147f190455AF3,22349480,0.084911,0.084568,0.084568
898,0xE800e3760FC20aA98c5df6A9816147f190455AF3,22356658,0.084474,0.084067,0.084067
899,0xE800e3760FC20aA98c5df6A9816147f190455AF3,22363838,0.081148,0.080760,0.080760

Index([                                       'autopool_vault_address',
                                                               'block',
                                      'weighted_average_total_apr_out',
                                       'weighted_average_total_apr_in',
                              'weighted_average_safe_backing_discount',
        ('0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', 'total_shares'),
           ('0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', 'total_nav'),
       ('0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', 'nav_per_share'),
        ('0x6dC3ce9C57b20131347FDc9089D740DAf6eB34c5', 'total_shares'),
           ('0x6dC3ce9C57b20131347FDc9089D740DAf6eB34c5', 'total_nav'),
       ('0x6dC3ce9C57b20131347FDc9089D740DAf6eB34c5', 'nav_per_share'),
        ('0xE800e3760FC20aA98c5df6A9816147f190455AF3', 'total_shares'),
           ('0xE800e3760FC20aA98c5df6A9816147f190455AF3', 'total_nav'),
       ('0xE800e3760FC20aA98c5df6A9816147f190455AF3', 'nav_per_share'),
        ('0x35911af1B570E26f668905595dEd133D01CD3E5a', 'total_shares'),
           ('0x35911af1B570E26f668905595dEd133D01CD3E5a', 'total_nav'),
       ('0x35911af1B570E26f668905595dEd133D01CD3E5a', 'nav_per_share')],
      dtype='object')

In [40]:
autopool_weighted_avgs_with_state_df.head(1).iloc[0]

autopool_vault_address                                         0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56
block                                                                                            20759464
weighted_average_total_apr_out                                                                        0.0
weighted_average_total_apr_in                                                                         0.0
weighted_average_safe_backing_discount                                                                0.0
(0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56, total_shares)                                       0.239949
(0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56, total_nav)                                          0.239949
(0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56, nav_per_share)                                           1.0
(0x6dC3ce9C57b20131347FDc9089D740DAf6eB34c5, total_shares)                                            0.0
(0x6dC3ce9C57b20131347FDc9089D740DAf6eB34c5, total_nav)                                               0.0
(0x6dC3ce9C57b20131347FDc9089D740DAf6eB34c5, nav_per_share)                                           1.0
(0xE800e3760FC20aA98c5df6A9816147f190455AF3, total_shares)                                       0.449884
(0xE800e3760FC20aA98c5df6A9816147f190455AF3, total_nav)                                          0.449884
(0xE800e3760FC20aA98c5df6A9816147f190455AF3, nav_per_share)                                           1.0
(0x35911af1B570E26f668905595dEd133D01CD3E5a, total_shares)                                            NaN
(0x35911af1B570E26f668905595dEd133D01CD3E5a, total_nav)                                               NaN
(0x35911af1B570E26f668905595dEd133D01CD3E5a, nav_per_share)                                           NaN
Name: 0, dtype: object

In [44]:
new_autopool_state_rows = []
chain = ALL_CHAINS[0]


def _extract_autopool_state(row: dict):
    new_autopool_state_rows.append(
        AutopoolStates(
            autopool_vault_address=row["autopool_vault_address"],
            block=int(row["block"]),
            chain_id=chain.chain_id,
            total_shares=row[(row["autopool_vault_address"], "total_shares")],
            total_nav=row[(row["autopool_vault_address"], "total_nav")],
            nav_per_share=row[(row["autopool_vault_address"], "nav_per_share")],
            weighted_average_total_apr_out=row["weighted_average_total_apr_out"],
            weighted_average_total_apr_in=row["weighted_average_total_apr_in"],
            weighted_average_safe_backing_discount=row["weighted_average_safe_backing_discount"],
        )
    )


autopool_weighted_avgs_with_state_df.apply(_extract_autopool_state, axis=1)

new_autopool_state_rows

[AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20759464, total_shares=0.23994860869514073, total_nav=0.23994860869514073, nav_per_share=1.0, weighted_average_total_apr_out=0.0, weighted_average_total_apr_in=0.0, weighted_average_safe_backing_discount=0.0),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20766617, total_shares=944.0811157622477, total_nav=944.0811157622477, nav_per_share=1.0, weighted_average_total_apr_out=0.0, weighted_average_total_apr_in=0.0, weighted_average_safe_backing_discount=0.0),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20773761, total_shares=1654.3923628226087, total_nav=1654.3845347543415, nav_per_share=0.9999952683121349, weighted_average_total_apr_out=0.00605904752973822, weighted_average_total_apr_in=0.006023685909272614, weighted_average_safe_backing_discount=0.006023685909272614),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20780916, total_shares=3133.620122924308, total_nav=3133.3270675143185, nav_per_share=0.9999064802373951, weighted_average_total_apr_out=0.016018901112921147, weighted_average_total_apr_in=0.01592206581004041, weighted_average_safe_backing_discount=0.01592206581004041),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20788084, total_shares=3903.8147599344393, total_nav=3901.645343411692, nav_per_share=0.9994442829242277, weighted_average_total_apr_out=0.033280009851788674, weighted_average_total_apr_in=0.03302431763423734, weighted_average_safe_backing_discount=0.03302431763423734),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20795238, total_shares=4176.988230139352, total_nav=4174.454156946722, nav_per_share=0.9993933252733764, weighted_average_total_apr_out=0.038470640653806745, weighted_average_total_apr_in=0.03826813142273692, weighted_average_safe_backing_discount=0.03826813142273692),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20802389, total_shares=4275.487255426126, total_nav=4273.1136923634, nav_per_share=0.999444843845643, weighted_average_total_apr_out=0.051781401577394706, weighted_average_total_apr_in=0.05162310324473197, weighted_average_safe_backing_discount=0.05162310324473197),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20809562, total_shares=4400.6981559724745, total_nav=4398.3005485541735, nav_per_share=0.9994551756713768, weighted_average_total_apr_out=0.06112682524598824, weighted_average_total_apr_in=0.06103556572535951, weighted_average_safe_backing_discount=0.06103556572535951),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20816725, total_shares=5027.473443885452, total_nav=5025.04153824189, nav_per_share=0.9995162767798365, weighted_average_total_apr_out=0.06269780542188451, weighted_average_total_apr_in=0.06264458381496593, weighted_average_safe_backing_discount=0.06264458381496593),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20823901, total_shares=5573.178610954791, total_nav=5571.095914266966, nav_per_share=0.9996263000285452, weighted_average_total_apr_out=0.059357982860831715, weighted_average_total_apr_in=0.05930485617256846, weighted_average_safe_backing_discount=0.05930485617256846),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20831060, total_shares=5582.932662521496, total_nav=5578.17846354118, nav_per_share=0.999148440565613, weighted_average_total_apr_out=0.06604345993593577, weighted_average_total_apr_in=0.06534858618857754, weighted_average_safe_backing_discount=0.06534858618857754),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20838231, total_shares=5947.936032529838, total_nav=5943.136190022292, nav_per_share=0.9991930238520899, weighted_average_total_apr_out=0.06428593982540787, weighted_average_total_apr_in=0.06359762268185012, weighted_average_safe_backing_discount=0.06359762268185012),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20845405, total_shares=6294.014992382429, total_nav=6294.146484639984, nav_per_share=1.000020891633991, weighted_average_total_apr_out=0.0627627577065461, weighted_average_total_apr_in=0.062252041018826795, weighted_average_safe_backing_discount=0.062252041018826795),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20852572, total_shares=6407.394214802807, total_nav=6411.9542455670135, nav_per_share=1.000711682567255, weighted_average_total_apr_out=990760760.9475377, weighted_average_total_apr_in=981712263.597977, weighted_average_safe_backing_discount=981712263.597977),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20859740, total_shares=6641.051633500115, total_nav=6646.826346803014, nav_per_share=1.0008695480206429, weighted_average_total_apr_out=2033950068.7101688, weighted_average_total_apr_in=2014150304.3503768, weighted_average_safe_backing_discount=2014150304.3503768),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20866918, total_shares=6613.589509479281, total_nav=6620.042418282846, nav_per_share=1.0009757044634104, weighted_average_total_apr_out=2224106112.9043217, weighted_average_total_apr_in=2200640398.551946, weighted_average_safe_backing_discount=2200640398.551946),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20874085, total_shares=6935.800399011601, total_nav=6943.006006005791, nav_per_share=1.0010389005709013, weighted_average_total_apr_out=2078634133.561297, weighted_average_total_apr_in=2056565973.8600104, weighted_average_safe_backing_discount=2056565973.8600104),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20881261, total_shares=7542.695200790087, total_nav=7551.09241624847, nav_per_share=1.001113291102828, weighted_average_total_apr_out=2267044540.4533825, weighted_average_total_apr_in=2242181631.969263, weighted_average_safe_backing_discount=2242181631.969263),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20888424, total_shares=8154.93923602517, total_nav=8165.209462500885, nav_per_share=1.001259387247221, weighted_average_total_apr_out=1989463938.2699144, weighted_average_total_apr_in=1972032199.6602528, weighted_average_safe_backing_discount=1972032199.6602528),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20895606, total_shares=8258.526663628183, total_nav=8269.090285641472, nav_per_share=1.0012791170197237, weighted_average_total_apr_out=2077195153.149504, weighted_average_total_apr_in=2054916282.4315841, weighted_average_safe_backing_discount=2054916282.4315841),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20902784, total_shares=9342.992158320361, total_nav=9354.281347449272, nav_per_share=1.0012083055339887, weighted_average_total_apr_out=1829128729.8156064, weighted_average_total_apr_in=1815358373.5479803, weighted_average_safe_backing_discount=1815358373.5479803),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20909955, total_shares=9617.979841821547, total_nav=9630.270016056234, nav_per_share=1.0012778332286836, weighted_average_total_apr_out=1749112646.307792, weighted_average_total_apr_in=1734952426.5799644, weighted_average_safe_backing_discount=1734952426.5799644),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20917130, total_shares=9929.090308224257, total_nav=9941.0046564357, nav_per_share=1.0011999435841141, weighted_average_total_apr_out=1687308594.959096, weighted_average_total_apr_in=32522900.12037435, weighted_average_safe_backing_discount=32522900.12037435),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20924302, total_shares=10082.067344170626, total_nav=10094.233959720312, nav_per_share=1.0012067580124546, weighted_average_total_apr_out=1637391934.8697286, weighted_average_total_apr_in=30972577.76120878, weighted_average_safe_backing_discount=30972577.76120878),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20931482, total_shares=10500.240537634007, total_nav=10511.823314051595, nav_per_share=1.001103096293468, weighted_average_total_apr_out=1561248442.1581652, weighted_average_total_apr_in=28752446.397166505, weighted_average_safe_backing_discount=28752446.397166505),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20938657, total_shares=10341.986308397905, total_nav=10354.273628832725, nav_per_share=1.0011881006286811, weighted_average_total_apr_out=1555489304.3328493, weighted_average_total_apr_in=28240747.088063028, weighted_average_safe_backing_discount=28240747.088063028),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20945811, total_shares=10420.038251495298, total_nav=10431.523771303973, nav_per_share=1.0011022531329985, weighted_average_total_apr_out=3206239226.3088403, weighted_average_total_apr_in=3171594046.802734, weighted_average_safe_backing_discount=3171594046.802734),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20952957, total_shares=10400.894012241859, total_nav=10413.097498256906, nav_per_share=1.0011733112558097, weighted_average_total_apr_out=3227489531.7200904, weighted_average_total_apr_in=3194861342.7807317, weighted_average_safe_backing_discount=3194861342.7807317),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20960089, total_shares=10446.637260406253, total_nav=10459.041266101714, nav_per_share=1.0011873682780652, weighted_average_total_apr_out=3069294217.8497148, weighted_average_total_apr_in=3028312290.727938, weighted_average_safe_backing_discount=3028312290.727938),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20967244, total_shares=10762.625724591784, total_nav=10776.216303729969, nav_per_share=1.0012627568296026, weighted_average_total_apr_out=3059617284.7591047, weighted_average_total_apr_in=3017535469.333605, weighted_average_safe_backing_discount=3017535469.333605),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20974401, total_shares=10610.635304998701, total_nav=10624.995812381243, nav_per_share=1.001353406932738, weighted_average_total_apr_out=3337940088.6354966, weighted_average_total_apr_in=3295669340.805685, weighted_average_safe_backing_discount=3295669340.805685),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20981560, total_shares=10495.401801289581, total_nav=10509.682611084147, nav_per_share=1.001360672994226, weighted_average_total_apr_out=4810384653.810213, weighted_average_total_apr_in=4732112866.2953005, weighted_average_safe_backing_discount=4732112866.2953005),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20988724, total_shares=10384.66855472104, total_nav=10398.88115443757, nav_per_share=1.001368613706026, weighted_average_total_apr_out=5515854791.105423, weighted_average_total_apr_in=5439268731.410559, weighted_average_safe_backing_discount=5439268731.410559),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=20995892, total_shares=10170.468852252337, total_nav=10184.632020233441, nav_per_share=1.0013925776861277, weighted_average_total_apr_out=5316427442.856434, weighted_average_total_apr_in=5240217228.6788, weighted_average_safe_backing_discount=5240217228.6788),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=21003063, total_shares=10160.08827511673, total_nav=10174.922082271023, nav_per_share=1.0014600077039313, weighted_average_total_apr_out=5166251253.55194, weighted_average_total_apr_in=5098255229.704299, weighted_average_safe_backing_discount=5098255229.704299),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=21010230, total_shares=10110.964292147484, total_nav=10127.28866855443, nav_per_share=1.0016145222092834, weighted_average_total_apr_out=4964054191.1508465, weighted_average_total_apr_in=115445217.0094461, weighted_average_safe_backing_discount=115445217.0094461),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=21017401, total_shares=10193.881322500085, total_nav=10211.196455638801, nav_per_share=1.0016985810007908, weighted_average_total_apr_out=4683955783.437479, weighted_average_total_apr_in=112404199.94243963, weighted_average_safe_backing_discount=112404199.94243963),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=21024558, total_shares=10033.767113184984, total_nav=10051.248347735898, nav_per_share=1.001742240412172, weighted_average_total_apr_out=5250501493.747051, weighted_average_total_apr_in=146130275.87159157, weighted_average_safe_backing_discount=146130275.87159157),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=21031733, total_shares=10097.175633203185, total_nav=10115.343645480407, nav_per_share=1.0017993162580514, weighted_average_total_apr_out=6110407395.293735, weighted_average_total_apr_in=5931104967.734391, weighted_average_safe_backing_discount=5931104967.734391),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=21038905, total_shares=10072.892713351208, total_nav=10091.403440091492, nav_per_share=1.0018376773452324, weighted_average_total_apr_out=5864587038.190543, weighted_average_total_apr_in=5791294723.826653, weighted_average_safe_backing_discount=5791294723.826653),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=21046076, total_shares=10117.427613033575, total_nav=10136.996629600384, nav_per_share=1.00193418893767, weighted_average_total_apr_out=5567958200.22318, weighted_average_total_apr_in=5497620031.594768, weighted_average_safe_backing_discount=5497620031.594768),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=21053236, total_shares=10877.098702790125, total_nav=10899.313349105489, nav_per_share=1.0020423319602374, weighted_average_total_apr_out=5097761443.973552, weighted_average_total_apr_in=5038636485.866901, weighted_average_safe_backing_discount=5038636485.866901),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=21060412, total_shares=10941.502930942135, total_nav=10964.44654674609, nav_per_share=1.0020969345755117, weighted_average_total_apr_out=4859510092.085406, weighted_average_total_apr_in=4803640449.463651, weighted_average_safe_backing_discount=4803640449.463651),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=21067570, total_shares=10829.48841290398, total_nav=10854.187379529729, nav_per_share=1.002280714072912, weighted_average_total_apr_out=4341205299.434045, weighted_average_total_apr_in=4290595607.9079742, weighted_average_safe_backing_discount=4290595607.9079742),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=21074738, total_shares=10813.704922993344, total_nav=10834.735947241705, nav_per_share=1.0019448490964131, weighted_average_total_apr_out=5403662365.303025, weighted_average_total_apr_in=5297490676.100143, weighted_average_safe_backing_discount=5297490676.100143),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=21081894, total_shares=10814.068672330633, total_nav=10835.665901347309, nav_per_share=1.0019971418409739, weighted_average_total_apr_out=5662724920.048237, weighted_average_total_apr_in=5545306774.124778, weighted_average_safe_backing_discount=5545306774.124778),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=21089068, total_shares=10820.590847165277, total_nav=10843.161533955481, nav_per_share=1.002085901510278, weighted_average_total_apr_out=4487227644.629645, weighted_average_total_apr_in=4376704784.687503, weighted_average_safe_backing_discount=4376704784.687503),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=21096238, total_shares=10692.766944083272, total_nav=10716.561041668218, nav_per_share=1.002225251678015, weighted_average_total_apr_out=4780702919.412992, weighted_average_total_apr_in=4660625011.977415, weighted_average_safe_backing_discount=4660625011.977415),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=21103392, total_shares=10696.93838715671, total_nav=10721.037170698779, nav_per_share=1.0022528673784832, weighted_average_total_apr_out=4941554339.734908, weighted_average_total_apr_in=4828315459.395562, weighted_average_safe_backing_discount=4828315459.395562),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=21110559, total_shares=10786.845265071985, total_nav=10813.469553620876, nav_per_share=1.0024682182690707, weighted_average_total_apr_out=5002044908.229968, weighted_average_total_apr_in=4887430732.90215, weighted_average_safe_backing_discount=4887430732.90215),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=21117728, total_shares=10516.483694017612, total_nav=10544.30620297723, nav_per_share=1.002645609480234, weighted_average_total_apr_out=5152687946.494031, weighted_average_total_apr_in=5038870553.708044, weighted_average_safe_backing_discount=5038870553.708044),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=21124888, total_shares=10515.280386309434, total_nav=10544.610083171774, nav_per_share=1.0027892453443776, weighted_average_total_apr_out=5795669965.084972, weighted_average_total_apr_in=5677077941.478481, weighted_average_safe_backing_discount=5677077941.478481),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=21132050, total_shares=10325.894779900143, total_nav=10355.491417951669, nav_per_share=1.0028662540808704, weighted_average_total_apr_out=5665183386.345299, weighted_average_total_apr_in=5533771261.666408, weighted_average_safe_backing_discount=5533771261.666408),
 AutopoolStates(autopool_vault_address='0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56', chain_id=1, block=21139209, total_shares=10345.065754175417, total_nav=10375.83513298899, nav_per_share=1.0029743048081792, weighted_average_total_apr_out=5897511463.70293, weighted_average_total_apr_in=5783872620.088398, weighted_average_safe_backing_discount=5783872620.088398),

In [ ]:
# full

In [27]:
autopool_state_df

,"(0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56, total_shares)","(0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56, total_nav)","(0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56, nav_per_share)","(0x6dC3ce9C57b20131347FDc9089D740DAf6eB34c5, total_shares)","(0x6dC3ce9C57b20131347FDc9089D740DAf6eB34c5, total_nav)","(0x6dC3ce9C57b20131347FDc9089D740DAf6eB34c5, nav_per_share)","(0xE800e3760FC20aA98c5df6A9816147f190455AF3, total_shares)","(0xE800e3760FC20aA98c5df6A9816147f190455AF3, total_nav)","(0xE800e3760FC20aA98c5df6A9816147f190455AF3, nav_per_share)","(0x35911af1B570E26f668905595dEd133D01CD3E5a, total_shares)","(0x35911af1B570E26f668905595dEd133D01CD3E5a, total_nav)","(0x35911af1B570E26f668905595dEd133D01CD3E5a, nav_per_share)",block
timestamp,,,,,,,,,,,,,
2024-09-15 23:59:59+00:00,0.239949,0.239949,1.000000,1.000000e-13,1.000000e-13,1.000000,0.449884,0.449884,1.000000,NaN,NaN,NaN,20759464
2024-09-16 23:59:59+00:00,944.081116,944.081116,1.000000,6.109170e+02,6.107142e+02,0.999668,398.277626,398.277626,1.000000,NaN,NaN,NaN,20766617
2024-09-17 23:59:59+00:00,1654.392363,1654.384535,0.999995,1.025542e+03,1.024945e+03,0.999418,641.320724,641.244644,0.999881,NaN,NaN,NaN,20773761
2024-09-18 23:59:59+00:00,3133.620123,3133.327068,0.999906,1.817276e+03,1.815990e+03,0.999293,1149.219706,1148.786322,0.999623,NaN,NaN,NaN,20780916
2024-09-19 23:59:59+00:00,3903.814760,3901.645343,0.999444,1.947166e+03,1.945543e+03,0.999166,1389.852544,1389.059253,0.999429,NaN,NaN,NaN,20788084
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-04-23 23:59:59+00:00,13320.745844,13784.771713,1.034835,1.081396e+03,1.117050e+03,1.032970,478.869466,494.136743,1.031882,849.224032,860.944075,1.013801,22335153
2025-04-24 23:59:59+00:00,13340.566677,13806.582560,1.034932,1.078953e+03,1.114605e+03,1.033043,478.874032,494.267685,1.032146,849.244736,861.046513,1.013897,22342307
2025-04-25 23:59:59+00:00,14054.739402,14546.090669,1.034960,1.044624e+03,1.079424e+03,1.033313,478.871718,494.262104,1.032139,831.800530,843.439884,1.013993,22349480
2025-04-26 23:59:59+00:00,14029.470355,14521.845807,1.035096,1.044454e+03,1.079488e+03,1.033543,478.878421,494.403562,1.032420,832.003494,843.708763,1.014069,22356658
2025-04-27 23:59:59+00:00,14023.656780,14520.384977,1.035421,1.031509e+03,1.066242e+03,1.033672,478.877992,494.443413,1.032504,832.051372,844.011921,1.014375,22363838

In [ ]:
# weighted_average_total_apr_out: Mapped[float] = mapped_column(nullable=False)
# weighted_average_total_apr_in: Mapped[float] = mapped_column(nullable=False)
# weighted_average_safe_backing_discount: Mapped[float] = mapped_column(nullable=False)  # price return

In [5]:
wide_autopool_destination_df.columns

Index(['chain_id', 'block', 'destination_vault_address',
       'autopool_vault_address', 'amount', 'total_safe_value',
       'total_spot_value', 'total_backing_value', 'percent_ownership',
       'incentive_apr', 'fee_apr', 'base_apr', 'points_apr',
       'fee_plus_base_apr', 'total_apr_in', 'total_apr_out',
       'underlying_token_total_supply', 'safe_total_supply', 'price_per_share',
       'price_return', 'underlying_safe_price', 'underlying_spot_price',
       'underlying_backing', 'safe_backing_discount', 'spot_backing_discount',
       'safe_spot_spread'],
      dtype='object')

In [ ]:
autopool_total_destination_safe_value_by_block = (
    wide_autopool_destination_df.groupby(["autopool_vault_address", "block"])["total_safe_value"].sum().reset_index()
)
autopool_total_destination_safe_value_by_block.columns = [
    "autopool_vault_address",
    "block",
    "autopool_total_safe_value",
]

                          autopool_vault_address     block  total_safe_value
0     0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56  20759464          0.000000
1     0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56  20766617          0.000000
2     0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56  20773761         99.989238
3     0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56  20780916        560.414095
4     0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56  20788084       1429.848335
...                                          ...       ...               ...
1067  0xE800e3760FC20aA98c5df6A9816147f190455AF3  22327989        491.964071
1068  0xE800e3760FC20aA98c5df6A9816147f190455AF3  22335153        492.076268
1069  0xE800e3760FC20aA98c5df6A9816147f190455AF3  22342307        491.988405
1070  0xE800e3760FC20aA98c5df6A9816147f190455AF3  22349480        492.079276
1071  0xE800e3760FC20aA98c5df6A9816147f190455AF3  22356658        492.065171

[1072 rows x 3 columns]

In [2]:
limited_destination_states_df = destination_states_df[
    [
        "destination_vault_address",
        "block",
        "underlying_token_total_supply",
        "underlying_safe_price",
        "underlying_spot_price",
        "underlying_backing",
        "chain_id",
    ]
].copy()
autopool_destination_balance_of_df

,block,autopool_vault_address,destination_vault_address,balance_of
0,20759464.0,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,0.000000
1,20759464.0,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,0x865e59D439BF7310c9BC6117E6020B8C87De4065,0.000000
2,20759464.0,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,0x25cb41919d6B88e0D48108A4F5fe8FBb3744aFE1,0.000000
3,20759464.0,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,0x6DcB6797b1C0442587c2ad79745ef7BB487Fc2E2,0.000000
4,20759464.0,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,0xe3AE2Ab9AE8ADe1B4940dd893C9339401bEe61A1,0.000000
...,...,...,...,...
15003,22356658.0,0xE800e3760FC20aA98c5df6A9816147f190455AF3,0x60339056EC88996e41757E05a798310E46972cca,0.000000
15004,22356658.0,0xE800e3760FC20aA98c5df6A9816147f190455AF3,0x5c6aeb9ef0d5BbA4E6691f381003503FD0D45126,470.519208
15005,22356658.0,0x35911af1B570E26f668905595dEd133D01CD3E5a,0xc4Eb861e7b66f593482a3D7E8adc314f6eEDA30B,317.661117
15006,22356658.0,0x35911af1B570E26f668905595dEd133D01CD3E5a,0xe4433D00Cf48BFE0C672d9949F2cd2c008bffC04,0.000000
15007,22356658.0,0x35911af1B570E26f668905595dEd133D01CD3E5a,0xbA1462f43c6f60ebD1C62735c94E428aD073E01A,523.014004