In [31]:
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
import streamlit as st
import psutil

from mainnet_launch.constants import *

from mainnet_launch.database.schema.full import *
from mainnet_launch.database.schema.postgres_operations import merge_tables_as_df, TableSelector, get_full_table_as_df

df = merge_tables_as_df(
    selectors=[
        TableSelector(
            table=AutopoolDestinationStates,
        ),
        TableSelector(
            table=Destinations,
            join_on=(
                (Destinations.destination_vault_address == AutopoolDestinationStates.destination_vault_address)
                & (Destinations.chain_id == AutopoolDestinationStates.chain_id)
            ),
            select_fields=[Destinations.pool_type, Destinations.underlying_symbol, Destinations.exchange_name],
        ),
        TableSelector(
            table=DestinationStates,
            select_fields=[
                DestinationStates.incentive_apr,
                DestinationStates.fee_apr,
                DestinationStates.base_apr,
                DestinationStates.lp_token_safe_price,
                DestinationStates.total_apr_out,
                DestinationStates.total_apr_in,
            ],
            join_on=(
                (AutopoolDestinationStates.destination_vault_address == DestinationStates.destination_vault_address)
                & (AutopoolDestinationStates.chain_id == DestinationStates.chain_id)
                & (AutopoolDestinationStates.block == DestinationStates.block)
            ),
        ),
        TableSelector(
            table=Blocks,
            join_on=(
                (AutopoolDestinationStates.block == Blocks.block)
                & (AutopoolDestinationStates.chain_id == Blocks.chain_id)
            ),
            select_fields=[Blocks.datetime],
        ),
    ],
    # your global filter (you can also push this into a per‑selector row_filter if you prefer)
    where_clause=(
        (AutopoolDestinationStates.autopool_vault_address == AUTO_USD.autopool_eth_addr)
    ),
    order_by=Blocks.datetime,
    order="asc",
)
df

2025-05-16 16:51:39,273 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-05-16 16:51:39,274 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-05-16 16:51:39,274 INFO sqlalchemy.engine.Engine [cached since 397.6s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x13dec8e80>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-05-16 16:51:39,274 INFO sqlalchemy.engine.Engine SELECT
    autopool_destination_states.*,
    destinations.pool_type,
    destinations.underlying_symbol,
    destinations.exchange_name,
    destination_states.incentive_apr,
    destination_states.fee_apr,
    destination_states.base_apr,
    destination_states.lp_token_safe_price,
    destination_states.total_apr_out,
    destination_states.total_apr_in,
    blocks.datetime
FROM autopool_destination_states
JOIN destinations
  ON destinations.destination_vault_address = autopool_destination_states.destination_vault_address AND destinations.chain_id = autopool_destination_states.chain_id
JOIN destination_states
  ON autopool_destination_states.destination_vault_address = destination_states.destination_vault_address AND autopool_destination_states.chain_id = destination_states.chain_id AND autopool_destination_states.block = destination_states.block
JOIN blocks
  ON autopool_destination_states.block = blocks.block AND autopool_destination_states.chain_id = blocks.chain_id
WHERE
    (autopool_destination_states.autopool_vault_address = '0xa7569A44f348d3D70d8ad5889e50F78E33d80D35')
ORDER BY
    blocks.datetime ASC

2025-05-16 16:51:39,275 INFO sqlalchemy.engine.Engine [cached since 397.6s ago] {}
2025-05-16 16:51:40,310 INFO sqlalchemy.engine.Engine ROLLBACK

,destination_vault_address,autopool_vault_address,block,chain_id,owned_shares,pool_type,underlying_symbol,exchange_name,incentive_apr,fee_apr,base_apr,lp_token_safe_price,total_apr_out,total_apr_in,datetime
0,0xa767F35BF1d51f4ab7432188DfE6324934c9CCbD,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22163007,1,0.000000e+00,self,sUSDS,none,0.000000,None,None,1.045833,0.054418,0.054418,2025-03-30 23:26:47+00:00
1,0xc46806911906248117Bbe87aC6e2814436Ad9fbe,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22163007,1,0.000000e+00,self,scrvUSD,none,0.000000,None,None,1.042612,0.018782,0.018782,2025-03-30 23:26:47+00:00
2,0x77fa99c62e746C98a7c24d0EFA2120F4eee9a993,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22163007,1,0.000000e+00,self,sDAI,none,0.000000,None,None,1.153297,0.044883,0.044883,2025-03-30 23:26:47+00:00
3,0x04ee6c666a01018a070925040ea2aF6554d051e4,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22163007,1,0.000000e+00,curveNG,MtEthena,curve,0.000000,None,None,1.143337,0.054237,0.054237,2025-03-30 23:26:47+00:00
4,0x6F628dcCD275feA4277722D177265741031E09d7,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22163007,1,0.000000e+00,curveV1,crvUSDUSDT-f,curve,0.097897,None,None,1.016856,0.093448,0.093448,2025-03-30 23:26:47+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11151,0x3Ee3F7A0B244004B0678EBa98bA091eC101513Ee,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22494972,1,2.730671e+06,curveNG,SkySaver,curve,0.032875,None,None,1.035324,0.061384,0.061384,2025-05-16 10:14:23+00:00
11152,0x769C6bEA7db25F4c0a52f0dB0960c42F708DBF41,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22494972,1,0.000000e+00,aTokenStataV3,waEthUSDC,aave,0.000000,None,None,1.129071,0.037260,0.037260,2025-05-16 10:14:23+00:00
11153,0xE4545f9dBC30Ccb6Cda6930DDFd69f3D419FcB61,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22494972,1,0.000000e+00,fToken,fUSDT,fluid,0.035100,None,None,1.145468,0.058234,0.058234,2025-05-16 10:14:23+00:00
11154,0x734FE415357c9c585794892405dCD714c5Ae68c5,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22494972,1,0.000000e+00,self,sFRAX,frax,0.000000,None,None,1.127886,0.044961,0.044961,2025-05-16 10:14:23+00:00
11155,0xc73aF8064EcbfcCBF687cF36a8ABaFf011eAB1fC,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22494972,1,0.000000e+00,self,sUSDe,ethena,0.000000,None,None,1.172634,0.074107,0.074107,2025-05-16 10:14:23+00:00

In [ ]:
dest_df = get_full_table_as_df(Destinations)

2025-05-16 16:52:48,385 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-05-16 16:52:48,385 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-05-16 16:52:48,386 INFO sqlalchemy.engine.Engine [cached since 466.7s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x13d614eb0>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-05-16 16:52:48,386 INFO sqlalchemy.engine.Engine
            SELECT *
            FROM destinations


2025-05-16 16:52:48,387 INFO sqlalchemy.engine.Engine [generated in 0.00068s] {}
2025-05-16 16:52:48,769 INFO sqlalchemy.engine.Engine ROLLBACK

,destination_vault_address,chain_id,exchange_name,name,symbol,pool_type,pool,underlying,underlying_symbol,underlying_name,denominated_in
0,0x003aD6a060a1082B7A6F85d24dDF9E9E196B8426,1,balancer,Tokemak-Wrapped Ether-Gyroscope ECLP wstETH/wETH,toke-WETH-ECLP-wstETH-wETH,balGyro,0xf01b0684C98CD7aDA480BFDF6e43876422fa1Fc1,0xf01b0684C98CD7aDA480BFDF6e43876422fa1Fc1,ECLP-wstETH-wETH,Gyroscope ECLP wstETH/wETH,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
1,0x734FE415357c9c585794892405dCD714c5Ae68c5,1,frax,Tokemak-USD Coin-Staked FRAX,toke-USDC-sFRAX,self,0xA663B02CF0a4b149d2aD41910CB81e23e1c41c32,0xA663B02CF0a4b149d2aD41910CB81e23e1c41c32,sFRAX,Staked FRAX,0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
2,0x2B08137BeABd2454AD3631DEB754F97C5c93eB78,1,curve,Tokemak-Wrapped Ether-wETH/rETH,toke-WETH-wETHrETH,curveNG,0x9EfE1A1Cbd6Ca51Ee8319AFc4573d253C3B732af,0x9EfE1A1Cbd6Ca51Ee8319AFc4573d253C3B732af,wETHrETH,wETH/rETH,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
3,0x6F628dcCD275feA4277722D177265741031E09d7,1,curve,Tokemak-USD Coin-Curve.fi Factory Plain Pool: ...,toke-USDC-crvUSDUSDT-f,curveV1,0x390f3595bCa2Df7d23783dFd126427CCeb997BF4,0x390f3595bCa2Df7d23783dFd126427CCeb997BF4,crvUSDUSDT-f,Curve.fi Factory Plain Pool: crvUSD/USDT,0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
4,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,1,tokemak,autoETH,autoETH,idle,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,autoETH,autoETH,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
...,...,...,...,...,...,...,...,...,...,...,...
116,0x945a4f719018edBa445ca67bDa43663C815835Ad,8453,aerodrome,Tokemak-Wrapped Ether-Volatile AMM - weETH.bas...,toke-WETH-vAMM-weETH.base/WETH,vAMM,0x91F0f34916Ca4E2cCe120116774b0e4fA0cdcaA8,0x91F0f34916Ca4E2cCe120116774b0e4fA0cdcaA8,vAMM-weETH.base/WETH,Volatile AMM - weETH.base/WETH,0x4200000000000000000000000000000000000006
117,0xb3723E69D6e4553239d7dAf514bF8ff7998500E0,8453,balancer,Tokemak-Wrapped Ether-Balancer weETH/wETH,toke-WETH-weETH/wETH,balCompStable,0xaB99a3e856dEb448eD99713dfce62F937E2d4D74,0xaB99a3e856dEb448eD99713dfce62F937E2d4D74,weETH/wETH,Balancer weETH/wETH,0x4200000000000000000000000000000000000006
118,0xa6EFB95B7393cB419B48A933273F49b6bb48dd5D,8453,balancer,Tokemak-Wrapped Ether-Balancer rETH-WETH Stabl...,toke-WETH-rETH-WETH-BPT,balCompStable,0xC771c1a5905420DAEc317b154EB13e4198BA97D0,0xC771c1a5905420DAEc317b154EB13e4198BA97D0,rETH-WETH-BPT,Balancer rETH-WETH Stable Pool,0x4200000000000000000000000000000000000006
119,0xA94031Ed4b316B043464FDd5482877F42A39845a,8453,aerodrome,Tokemak-Wrapped Ether-Volatile AMM - WETH/wrsETH,toke-WETH-vAMM-WETH/wrsETH,vAMM,0xA24382874A6FD59de45BbccFa160488647514c28,0xA24382874A6FD59de45BbccFa160488647514c28,vAMM-WETH/wrsETH,Volatile AMM - WETH/wrsETH,0x4200000000000000000000000000000000000006
120,0xBd137c56f3116E5c36753037a784FF844F84F59c,8453,balancer,Tokemak-Wrapped Ether-Gyroscope ECLP cbETH/wstETH,toke-WETH-ECLP-cbETH-wstETH,balGyro,0x54D86E177cdC664B5F9B17eB5fd6A76Fa529e466,0x54D86E177cdC664B5F9B17eB5fd6A76Fa529e466,ECLP-cbETH-wstETH,Gyroscope ECLP cbETH/wstETH,0x4200000000000000000000000000000000000006

In [37]:
states_df = get_full_table_as_df(DestinationStates)
states_df

2025-05-16 16:54:20,160 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-05-16 16:54:20,161 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-05-16 16:54:20,161 INFO sqlalchemy.engine.Engine [cached since 558.5s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x13d2672b0>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-05-16 16:54:20,162 INFO sqlalchemy.engine.Engine
            SELECT *
            FROM destination_states


2025-05-16 16:54:20,162 INFO sqlalchemy.engine.Engine [generated in 0.00029s] {}
2025-05-16 16:54:21,227 INFO sqlalchemy.engine.Engine ROLLBACK

,destination_vault_address,block,chain_id,incentive_apr,fee_apr,base_apr,points_apr,fee_plus_base_apr,total_apr_in,total_apr_out,underlying_token_total_supply,safe_total_supply,lp_token_spot_price,lp_token_safe_price,from_rebalance_plan
0,0x689dc7B5CE8e23061a8223E97701E9345764B8B7,21461471,1,0.055050,0.018044,0.012132,0.0,NaN,0.079721,0.080571,3313.727227,3055.219793,1.019245,1.019122,False
1,0x865e59D439BF7310c9BC6117E6020B8C87De4065,21654814,1,NaN,NaN,NaN,0.0,NaN,NaN,NaN,17733.170908,NaN,1.015369,1.015377,False
2,0xE93f9C1f6436c7dCb3FE094E13E58742E16ae848,21962635,1,0.046937,0.022654,0.016525,0.0,NaN,0.081422,0.081919,1686.224391,1676.697361,1.036440,1.036359,False
3,0x356c79Ab2B2cEFAB685004CE827146058A6c3e77,21984128,1,NaN,NaN,NaN,0.0,NaN,NaN,NaN,6022.062314,NaN,0.997752,0.989108,False
4,0x2B08137BeABd2454AD3631DEB754F97C5c93eB78,21826720,1,0.032234,0.025018,0.018710,0.0,NaN,0.072738,0.075402,292.309865,287.317100,1.015684,1.015554,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28263,0x3F55eedDe51504E6Ed0ec30E8289b4Da11EdB7F9,22385293,1,NaN,0.028074,0.027572,0.0,NaN,NaN,NaN,6257.446552,0.000000,1.043313,1.043295,False
28264,0x3F55eedDe51504E6Ed0ec30E8289b4Da11EdB7F9,22442219,1,NaN,0.026926,0.027207,0.0,NaN,NaN,NaN,6271.145018,0.000000,1.042947,1.042946,False
28265,0x5c6aeb9ef0d5BbA4E6691f381003503FD0D45126,21339732,1,NaN,0.036924,0.017309,0.0,NaN,NaN,NaN,1863.283674,417.233610,1.034554,1.034541,False
28266,0x49895f72fd9d0BF6BBb485C70CE38556de62b070,22442219,1,NaN,0.026926,0.027207,0.0,NaN,NaN,NaN,6271.145018,0.000000,1.042947,1.042946,False
28267,0x49895f72fd9d0BF6BBb485C70CE38556de62b070,22385293,1,NaN,0.028074,0.027572,0.0,NaN,NaN,NaN,6257.446552,0.000000,1.043313,1.043295,False

In [38]:
states_df[states_df['destination_vault_address'] == AUTO_USD.autopool_eth_addr].T

Empty DataFrame
Columns: []
Index: [destination_vault_address, block, chain_id, incentive_apr, fee_apr, base_apr, points_apr, fee_plus_base_apr, total_apr_in, total_apr_out, underlying_token_total_supply, safe_total_supply, lp_token_spot_price, lp_token_safe_price, from_rebalance_plan]

In [28]:
df[df['destination_vault_address'] == df['autopool_vault_address']]

Empty DataFrame
Columns: [destination_vault_address, autopool_vault_address, block, chain_id, owned_shares, pool_type, underlying_symbol, exchange_name, incentive_apr, fee_apr, base_apr, lp_token_safe_price, total_apr_out, total_apr_in, datetime]
Index: []

In [22]:
df['underlying_symbol'].value_counts()

underlying_symbol
sUSDe                 539
sUSDS                 538
sDAI                  538
crvUSDUSDT-f          537
sFRAX                 535
crvUSDUSDC-f          535
scrvUSD               535
sUSDe/USDC            534
GHOcrvUSD             534
crvUSDFRAX-f          534
SkySaver              534
llamathena            534
crv2pool              534
crvU-sUSDe            534
crvUSDe               532
frxsUSDS              532
MtEthena              365
sUSDEsUSDS            364
fUSDT                 328
fUSDC                 328
gtUSDCcore            248
waEthUSDC             248
waEthUSDT             248
gtUSDC                248
steakUSDC             218
Aave GHO/USDT/USDC      2
Name: count, dtype: int64

In [23]:
df.sort_values('total_apr_in', ascending=False)[['block', 'destination_vault_address', 'incentive_apr']].head(10)

          block                   destination_vault_address  incentive_apr
10340  22468452  0xd7900d87069C815a299bdA7aFDcd7eEe98fe4b6c       0.152658
10386  22470088  0xd7900d87069C815a299bdA7aFDcd7eEe98fe4b6c       0.150999
10366  22469198  0xd7900d87069C815a299bdA7aFDcd7eEe98fe4b6c       0.149846
10409  22470974  0xd7900d87069C815a299bdA7aFDcd7eEe98fe4b6c       0.147199
10455  22474463  0xd7900d87069C815a299bdA7aFDcd7eEe98fe4b6c       0.143634
10485  22475777  0xd7900d87069C815a299bdA7aFDcd7eEe98fe4b6c       0.143562
10473  22475413  0xd7900d87069C815a299bdA7aFDcd7eEe98fe4b6c       0.142235
10553  22476509  0xd7900d87069C815a299bdA7aFDcd7eEe98fe4b6c       0.144447
10557  22476598  0xd7900d87069C815a299bdA7aFDcd7eEe98fe4b6c       0.144104
10530  22476142  0xd7900d87069C815a299bdA7aFDcd7eEe98fe4b6c       0.143270

In [24]:
px.histogram(df['total_apr_out'])

In [25]:
autoUSD_df = df[df["destination_vault_address"] == "0xa7569A44f348d3D70d8ad5889e50F78E33d80D35"].sort_values("block")

# this gives the quantity of
px.line(autoUSD_df, y=["quantity"], x="block")

In [30]:
AutopoolDestinationStates_df = get_full_table_as_df(
    AutopoolDestinationStates, where_clause=AutopoolDestinationStates.autopool_vault_address == AUTO_USD.autopool_eth_addr
)
AutopoolDestinationStates_df[AutopoolDestinationStates_df['autopool_vault_address'] == AutopoolDestinationStates_df['destination_vault_address']]

2025-05-16 16:50:18,912 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-05-16 16:50:18,913 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-05-16 16:50:18,913 INFO sqlalchemy.engine.Engine [cached since 317.2s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x138167f70>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-05-16 16:50:18,913 INFO sqlalchemy.engine.Engine
            SELECT *
            FROM autopool_destination_states
            WHERE autopool_destination_states.autopool_vault_address = '0xa7569A44f348d3D70d8ad5889e50F78E33d80D35'

2025-05-16 16:50:18,913 INFO sqlalchemy.engine.Engine [cached since 245.8s ago] {}
2025-05-16 16:50:19,894 INFO sqlalchemy.engine.Engine ROLLBACK

,destination_vault_address,autopool_vault_address,block,chain_id,owned_shares
34,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22492303,1,1.003914e+04
35,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22494972,1,1.153718e+06
124,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22163927,1,1.871042e+03
125,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22251984,1,1.030273e+06
142,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22258096,1,5.076340e+01
...,...,...,...,...,...
25996,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22267453,1,6.275937e+05
26012,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22368680,1,7.746454e+04
26050,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22238667,1,4.125851e+06
26084,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22310114,1,3.609373e+06
26339,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22332825,1,6.637833e+05

In [27]:
AutopoolDestinationStates_df[
    AutopoolDestinationStates_df["destination_vault_address"].str.lower()
    == AutopoolDestinationStates_df["autopool_vault_address"].str.lower()
]

,destination_vault_address,autopool_vault_address,block,chain_id,owned_shares
22,0x6dC3ce9C57b20131347FDc9089D740DAf6eB34c5,0x6dC3ce9C57b20131347FDc9089D740DAf6eB34c5,21038905,1,1.371545e+02
32,0xE800e3760FC20aA98c5df6A9816147f190455AF3,0xE800e3760FC20aA98c5df6A9816147f190455AF3,20809562,1,2.787124e+02
160,0x6dC3ce9C57b20131347FDc9089D740DAf6eB34c5,0x6dC3ce9C57b20131347FDc9089D740DAf6eB34c5,20809562,1,2.384426e+02
163,0x35911af1B570E26f668905595dEd133D01CD3E5a,0x35911af1B570E26f668905595dEd133D01CD3E5a,21038905,1,NaN
170,0xE800e3760FC20aA98c5df6A9816147f190455AF3,0xE800e3760FC20aA98c5df6A9816147f190455AF3,21038905,1,3.800329e+02
...,...,...,...,...,...
51511,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22267453,1,6.275937e+05
51527,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22368680,1,7.746454e+04
51565,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22238667,1,4.125851e+06
51599,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22310114,1,3.609373e+06
51854,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22332825,1,6.637833e+05