In [2]:
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
import streamlit as st
import psutil

from mainnet_launch.constants import AutopoolConstants

from mainnet_launch.database.schema.full import *
from mainnet_launch.database.schema.postgres_operations import merge_tables_as_df, TableSelector, get_full_table_as_df

df = get_full_table_as_df(DestinationTokenValues, where_clause=DestinationTokenValues.chain_id == 1)
df

2025-05-15 10:01:05,288 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-05-15 10:01:05,288 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-05-15 10:01:05,289 INFO sqlalchemy.engine.Engine [cached since 20.01s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x1726036a0>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-05-15 10:01:05,289 INFO sqlalchemy.engine.Engine
            SELECT *
            FROM destination_token_values
            WHERE destination_token_values.chain_id = 1

2025-05-15 10:01:05,289 INFO sqlalchemy.engine.Engine [cached since 20.01s ago] {}
2025-05-15 10:01:06,655 INFO sqlalchemy.engine.Engine ROLLBACK

          block  chain_id  ... spot_price     quantity
0      21397030         1  ...   1.185923     0.016910
1      20831060         1  ...   1.179774          NaN
2      21067570         1  ...   1.000017  1613.797382
3      22170334         1  ...   0.999670  1683.444096
4      22148848         1  ...   0.997668  4488.112240
...         ...       ...  ...        ...          ...
73551  21984128         1  ...        NaN          NaN
73552  22213305         1  ...        NaN          NaN
73553  22370998         1  ...        NaN          NaN
73554  21060412         1  ...        NaN          NaN
73555  22213305         1  ...        NaN          NaN

[73556 rows x 6 columns]

In [10]:
autoUSD_df = df[df["destination_vault_address"] == "0xa7569A44f348d3D70d8ad5889e50F78E33d80D35"].sort_values("block")


px.line(autoUSD_df, y=["quantity"], x="block")

In [12]:
AutopoolDestinationStates_df = get_full_table_as_df(
    AutopoolDestinationStates, where_clause=AutopoolDestinationStates.chain_id == 1
)
AutopoolDestinationStates_df

2025-05-15 10:05:52,587 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-05-15 10:05:52,587 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-05-15 10:05:52,587 INFO sqlalchemy.engine.Engine [cached since 307.3s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x1767d5600>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-05-15 10:05:52,588 INFO sqlalchemy.engine.Engine
            SELECT *
            FROM autopool_destination_states
            WHERE autopool_destination_states.chain_id = 1

2025-05-15 10:05:52,588 INFO sqlalchemy.engine.Engine [generated in 0.00020s] {}
2025-05-15 10:05:53,570 INFO sqlalchemy.engine.Engine ROLLBACK

                        destination_vault_address  ... owned_shares
0      0x1416BfE53520a71553230c3FdeeEce30d5470bA7  ...     0.000000
1      0x4E12227b350E8f8fEEc41A58D36cE2fB2e2d4575  ...     0.000000
2      0x3F55eedDe51504E6Ed0ec30E8289b4Da11EdB7F9  ...     0.000000
3      0x2F7e096a400ded5D02762120b39A3aA4ABA072a4  ...     0.000000
4      0x8cA2201BC34780f14Bca452913ecAc8e9928d4cA  ...     0.000000
...                                           ...  ...          ...
49540  0x6DcB6797b1C0442587c2ad79745ef7BB487Fc2E2  ...     0.000000
49541  0x867991C7737Ccbb152aE5a7E6EDB05cA0670717E  ...     0.000000
49542  0x1Ea622fa030e4a78F4CC2f305dd3c08DA3F08573  ...  1650.286018
49543  0x8cA2201BC34780f14Bca452913ecAc8e9928d4cA  ...     0.000000
49544  0x2899143298FECa3a36DAfDDcddAF167f1D673254  ...     0.000000

[49545 rows x 5 columns]

In [17]:
AutopoolDestinationStates_df[
    AutopoolDestinationStates_df["destination_vault_address"].str.lower()
    == AutopoolDestinationStates_df["autopool_vault_address"].str.lower()
]

Empty DataFrame
Columns: [destination_vault_address, autopool_vault_address, block, chain_id, owned_shares]
Index: []