In [1]:
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
import streamlit as st
import psutil

from mainnet_launch.constants import AutopoolConstants

from mainnet_launch.database.schema.full import *
from mainnet_launch.database.schema.postgres_operations import merge_tables_as_df, TableSelector, get_full_table_as_df

df = get_full_table_as_df(DestinationTokenValues, where_clause=DestinationTokenValues.chain_id == 1)
df

2025-05-15 14:26:07,236 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2025-05-15 14:26:07,237 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-05-15 14:26:07,425 INFO sqlalchemy.engine.Engine select current_schema()
2025-05-15 14:26:07,426 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-05-15 14:26:07,610 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2025-05-15 14:26:07,611 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-05-15 14:26:07,805 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-05-15 14:26:07,806 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-05-15 14:26:07,807 INFO sqlalchemy.engine.Engine [generated in 0.00144s] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x11bd364a0>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-05-15 14:26:07,807 INFO sqlalchemy.engine.Engine
            SELECT *
            FROM destination_token_values
            WHERE destination_token_values.chain_id = 1

2025-05-15 14:26:07,808 INFO sqlalchemy.engine.Engine [generated in 0.00082s] {}
2025-05-15 14:26:09,397 INFO sqlalchemy.engine.Engine ROLLBACK

,block,chain_id,token_address,destination_vault_address,denominated_in,spot_price,quantity
0,21404196,1,0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84,0xB84c580c005A5F633C8CF6eecAf5b0a8314EC5c4,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,0.998499,2.096855e+03
1,22335153,1,0xae78736Cd615f374D3085123A210448E74Fc6393,0x896eCc16Ab4AFfF6cE0765A5B924BaECd7Fa455a,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,1.126994,3.069341e+03
2,21139209,1,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,0x1Ea622fa030e4a78F4CC2f305dd3c08DA3F08573,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,1.000216,8.311536e+02
3,22070044,1,0x04C154b66CB340F3Ae24111CC767e0184Ed00Cc6,0xB84c580c005A5F633C8CF6eecAf5b0a8314EC5c4,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,0.995860,5.030314e+03
4,21991286,1,0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0,0x2899143298FECa3a36DAfDDcddAF167f1D673254,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,1.193905,2.205007e+02
...,...,...,...,...,...,...,...
74681,22347159,1,0x83F20F44975D03b1b09e64809B757c47f942BEeA,0xf0F2Eb4366AE0269022F7706A722F8795CDda0c5,0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48,1.157090,8.677499e+06
74682,22458975,1,0xdAC17F958D2ee523a2206206994597C13D831ec7,0x41A8DFc857554aE23A4b31188a3109EA4e2377D3,0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48,1.000010,2.786093e+06
74683,22397698,1,0x83F20F44975D03b1b09e64809B757c47f942BEeA,0xAd7b8dB1efEe849c67060c6b10BC7D6D3C607aa5,0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48,1.159815,7.373513e+06
74684,22257358,1,0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48,0x5996333aDf54e3aC8C0Fc3De0fe51de0B75BC00d,0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48,1.000112,1.960531e+07
74685,22252352,1,0xa3931d71877C0E7a3148CB7Eb4463524FEc27fbD,0xb949C40F18fB52747d96850696c954718168fde3,0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48,1.046536,1.275000e+07

In [2]:
autoUSD_df = df[df["destination_vault_address"] == "0xa7569A44f348d3D70d8ad5889e50F78E33d80D35"].sort_values("block")

# this gives the quantity of
px.line(autoUSD_df, y=["quantity"], x="block")

In [3]:
AutopoolDestinationStates_df = get_full_table_as_df(
    AutopoolDestinationStates, where_clause=AutopoolDestinationStates.chain_id == 1
)
AutopoolDestinationStates_df

2025-05-15 14:26:09,668 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-05-15 14:26:09,669 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-05-15 14:26:09,669 INFO sqlalchemy.engine.Engine [cached since 1.864s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x11e732110>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-05-15 14:26:09,670 INFO sqlalchemy.engine.Engine
            SELECT *
            FROM autopool_destination_states
            WHERE autopool_destination_states.chain_id = 1

2025-05-15 14:26:09,670 INFO sqlalchemy.engine.Engine [generated in 0.00032s] {}
2025-05-15 14:26:09,894 INFO sqlalchemy.engine.Engine ROLLBACK

,destination_vault_address,autopool_vault_address,block,chain_id,owned_shares
0,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,0x6dC3ce9C57b20131347FDc9089D740DAf6eB34c5,22306493,1,0.0
1,0x2f2CC1bf461413014741dD68481dB4a3686DAC3D,0xE800e3760FC20aA98c5df6A9816147f190455AF3,22306493,1,0.0
2,0x5A4B544B9734930DDC587c9a2f093dC5058A4f4D,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,21869537,1,0.0
3,0x6DcB6797b1C0442587c2ad79745ef7BB487Fc2E2,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,21869537,1,0.0
4,0x6DcB6797b1C0442587c2ad79745ef7BB487Fc2E2,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,22306493,1,0.0
...,...,...,...,...,...
303,0x7876F91BB22148345b3De16af9448081E9853830,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22164422,1,0.0
304,0xe6b267103A33f01bbcBbb5C247261fB3c040B387,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22163958,1,0.0
305,0x4a712BBFD80480eaEd9999DA8971B78DB2E12230,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22163958,1,0.0
306,0x04ee6c666a01018a070925040ea2aF6554d051e4,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22164422,1,0.0
307,0x4686CEe2B3b1Da28a1db926443d5DDd674462b29,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22163958,1,0.0

In [4]:
AutopoolDestinationStates_df[
    AutopoolDestinationStates_df["destination_vault_address"].str.lower()
    == AutopoolDestinationStates_df["autopool_vault_address"].str.lower()
]

,destination_vault_address,autopool_vault_address,block,chain_id,owned_shares
18,0xE800e3760FC20aA98c5df6A9816147f190455AF3,0xE800e3760FC20aA98c5df6A9816147f190455AF3,22306493,1,1.918628
67,0x35911af1B570E26f668905595dEd133D01CD3E5a,0x35911af1B570E26f668905595dEd133D01CD3E5a,21869537,1,0.549868
104,0xE800e3760FC20aA98c5df6A9816147f190455AF3,0xE800e3760FC20aA98c5df6A9816147f190455AF3,21869537,1,41.474854
132,0x6dC3ce9C57b20131347FDc9089D740DAf6eB34c5,0x6dC3ce9C57b20131347FDc9089D740DAf6eB34c5,22306493,1,5.882836
170,0x35911af1B570E26f668905595dEd133D01CD3E5a,0x35911af1B570E26f668905595dEd133D01CD3E5a,22306493,1,1.505569
182,0x6dC3ce9C57b20131347FDc9089D740DAf6eB34c5,0x6dC3ce9C57b20131347FDc9089D740DAf6eB34c5,21869537,1,30.753398
190,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,21869537,1,221.010955
191,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,22306493,1,87.509506
278,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22164422,1,1871.042034
300,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,0xa7569A44f348d3D70d8ad5889e50F78E33d80D35,22163958,1,1871.042034