In [ ]:
from mainnet_launch.constants import ALL_AUTOPOOLS, eth_client
from mainnet_launch.destination_diagnostics.fetch_destination_summary_stats import fetch_destination_summary_stats
from mainnet_launch.solver_diagnostics.fetch_rebalance_events import (
    fetch_and_clean_rebalance_between_destination_events,
    AUTOPOOL_ETH_STRATEGY_ABI,
    fetch_events,
)

dfs = {}
rebalance_dfs = {}
for autopool in ALL_AUTOPOOLS:
    strategy_contract = eth_client.eth.contract(autopool.autopool_eth_strategy_addr, abi=AUTOPOOL_ETH_STRATEGY_ABI)

    rebalance_between_destinations_df = fetch_events(strategy_contract.events.RebalanceBetweenDestinations)
    rebalance_dfs[autopool.name] = rebalance_between_destinations_df
    print(len(rebalance_between_destinations_df["block"]), autopool.name)

    uwcr_df, allocation_df, compositeReturn_out_df, total_nav_series, summary_stats_df = (
        fetch_destination_summary_stats(rebalance_between_destinations_df["block"].values, autopool)
    )
    percent_allocation_df = 100 * allocation_df.div(total_nav_series, axis=0)
    print(len(percent_allocation_df))
    dfs[autopool.name] = percent_allocation_df
    # TODO this evening
    # note this is surfacing a bigger problem, the blocks are not passe
    # allocation_df.to_csv(f'{autopool.name} allocation_after_rebalance_block.csv')
    # percent_allocation_df.to_csv(f'{autopool.name} percent_allocation_after_rebalance_block.csv')

2024-11-05 10:20:34.443 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-11-05 10:20:34.444 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-11-05 10:20:34.444 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-11-05 10:20:34.446 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-11-05 10:20:34.447 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-11-05 10:20:34.447 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-11-05 10:20:34.448 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-11-05 10:20:34.449 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

93 autoETH

2024-11-05 10:20:34.988 Thread 'Thread-13': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-11-05 10:20:35.305 Thread 'Thread-13': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-11-05 10:20:41.010 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-11-05 10:20:41.010 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-11-05 10:20:41.011 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-11-05 10:20:41.176 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-11-05 10:20:41.176 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-11-05 10:20:47.439 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-11-05 10:20:47.439 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

KeyboardInterrupt:

In [ ]:
dfs["autoETH"]

,B-rETH-STABLE (balancer),osETH/wETH-BPT (balancer),pxsteth (curve),wETHrETH (curve),frxeth-ng-f (curve),osETH-rETH (curve),wstETH-WETH-BPT (balancer),ETHx/wstETH (balancer),ECLP-wstETH-wETH (balancer),autoETH (tokemak),pxethweth (curve),ethx-f (curve),ECLP-wstETH-cbETH (balancer),pxETH/wETH (balancer)
timestamp,,,,,,,,,,,,,,
2024-09-15 02:04:47+00:00,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,100.000000,0.000000,0.000000,0.0,0.000000
2024-09-15 05:44:35+00:00,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,100.000000,0.000000,0.000000,0.0,0.000000
2024-09-15 09:24:47+00:00,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,100.000000,0.000000,0.000000,0.0,0.000000
2024-09-15 13:04:11+00:00,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,100.000000,0.000000,0.000000,0.0,0.000000
2024-09-15 16:44:23+00:00,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,100.000000,0.000000,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-11-04 23:23:23+00:00,0.0,0.0,15.061226,0.0,0.0,9.927780,0.0,0.0,0.0,0.406149,23.173629,23.682502,0.0,27.748714
2024-11-05 03:03:23+00:00,0.0,0.0,15.061172,0.0,0.0,9.927686,0.0,0.0,0.0,0.406155,23.173537,23.682863,0.0,27.748587
2024-11-05 06:44:11+00:00,0.0,0.0,15.059619,0.0,0.0,9.926771,0.0,0.0,0.0,0.415689,23.171355,23.680867,0.0,27.745699
2024-11-05 10:24:11+00:00,0.0,0.0,15.106731,0.0,0.0,9.949790,0.0,0.0,0.0,0.111771,23.243845,23.755392,0.0,27.832471
2024-11-05 14:04:11+00:00,0.0,0.0,15.106911,0.0,0.0,9.949895,0.0,0.0,0.0,0.112152,23.243496,23.755495,0.0,27.832051

In [ ]:
rebalance_dfs["autoLRT"]

,block,break_even_days,swapCost,apr_delta,out_compositeReturn,in_compositeReturn,predicted_increase_after_swap_cost,predicted_gain_during_swap_cost_off_set_period,inEthValue,outEthValue,out_destination,in_destination,offset_period,slippage,hash,moveName
timestamp,,,,,,,,,,,,,,,,
2024-09-17 02:30:23+00:00,20767364,2.420695,0.045368,6.642883,0.0,6.642883,0.891725,0.937093,102.979055,103.024424,autoLRT (tokemak),weeth-ng (curve),50,0.000440,0x5a6f3a2239134ef903468d88abce973e6b71e233af04...,autoLRT (tokemak) -> weeth-ng (curve)
2024-09-17 18:34:35+00:00,20772145,4.275412,0.137627,11.191440,0.0,11.191440,1.471893,1.609520,104.986473,105.124100,autoLRT (tokemak),rsETH / WETH (balancer),50,0.001309,0x46cfba2d4f806b97e71d9465ae05556bc41cb3635c5d...,autoLRT (tokemak) -> rsETH / WETH (balancer)
2024-09-18 15:13:59+00:00,20778301,6.484865,0.266500,8.904569,0.0,8.904569,1.788286,2.054786,168.452184,168.718684,autoLRT (tokemak),rsETH / ETHx (balancer),50,0.001580,0xa0ea869df690411f31e8a430670cfaea2b69a5849715...,autoLRT (tokemak) -> rsETH / ETHx (balancer)
2024-09-19 01:37:11+00:00,20781400,6.075920,0.246248,7.734454,0.0,7.734454,1.780176,2.026424,191.259679,191.505927,autoLRT (tokemak),rsETH / WETH (balancer),50,0.001286,0xca793ddcca9f1a355bf52d55d397068f49b8c43de799...,autoLRT (tokemak) -> rsETH / WETH (balancer)
2024-09-19 17:16:11+00:00,20786072,8.299679,0.255597,7.799456,0.0,7.799456,1.284205,1.539803,144.119783,144.375381,autoLRT (tokemak),rsETH / ETHx (balancer),50,0.001770,0x6ce994c065fa58c7b58d215373dcb7480aba63965013...,autoLRT (tokemak) -> rsETH / ETHx (balancer)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-30 18:31:23+00:00,21080256,5.430705,0.000993,5.840952,0.0,5.840952,0.007781,0.008773,1.142160,1.143153,autoLRT (tokemak),weETH/rETH (balancer),48,0.000868,0xf20872bde7372d3106cde489b5c44c8d2af1ef0003bb...,autoLRT (tokemak) -> weETH/rETH (balancer)
2024-11-02 18:23:59+00:00,21101723,5.782899,0.048031,6.570902,0.0,6.570902,0.350643,0.398674,46.136508,46.184539,autoLRT (tokemak),weETH/ezETH/rswETH (balancer),48,0.001040,0x80d0938d7a921128c6c03a5e445601f1521cd63c49e9...,autoLRT (tokemak) -> weETH/ezETH/rswETH (balan...
2024-11-03 05:14:23+00:00,21104953,7.197844,0.040551,5.943565,0.0,5.943565,0.229873,0.270424,34.597914,34.638465,autoLRT (tokemak),weETH/ezETH/rswETH (balancer),48,0.001171,0xede5866db4be0f6de1e525a9b1b0235cff05ba297f4b...,autoLRT (tokemak) -> weETH/ezETH/rswETH (balan...
2024-11-03 15:39:59+00:00,21108066,3.809324,0.016759,5.982922,0.0,5.982922,0.194411,0.211170,26.839244,26.856002,autoLRT (tokemak),weETH/rETH (balancer),48,0.000624,0xdacddd6ad041529eb01703f2df2daf1b6c61fa0ade5d...,autoLRT (tokemak) -> weETH/rETH (balancer)
2024-11-04 00:33:23+00:00,21110724,5.491870,0.070480,5.854611,0.0,5.854611,0.545527,0.616007,80.009023,80.079503,autoLRT (tokemak),weETH/rETH (balancer),48,0.000880,0xe57c877eadb11667cd753e412786306f7f3d78b8bf1b...,autoLRT (tokemak) -> weETH/rETH (balancer)

In [ ]:
dfs["autoLRT"]

,ezETH-WETH-BPT (balancer),rsETH / WETH (balancer),autoLRT (tokemak),weETH/ezETH/rswETH (balancer),weeth-ng (curve),rsETH / ETHx (balancer),weETH/rETH (balancer)
timestamp,,,,,,,
2024-09-15 02:04:47+00:00,0.0,0.000000,100.000000,0.000000,0.0,0.000000,0.000000
2024-09-15 05:44:35+00:00,0.0,0.000000,100.000000,0.000000,0.0,0.000000,0.000000
2024-09-15 09:24:47+00:00,0.0,0.000000,100.000000,0.000000,0.0,0.000000,0.000000
2024-09-15 13:04:11+00:00,0.0,0.000000,100.000000,0.000000,0.0,0.000000,0.000000
2024-09-15 16:44:23+00:00,0.0,0.000000,100.000000,0.000000,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...
2024-11-04 23:23:23+00:00,0.0,61.129919,7.734411,2.531780,0.0,4.278130,24.325761
2024-11-05 03:03:23+00:00,0.0,61.131849,7.734348,2.531739,0.0,4.278095,24.323969
2024-11-05 06:44:11+00:00,0.0,61.131318,7.735786,2.531738,0.0,4.278026,24.323131
2024-11-05 10:24:11+00:00,0.0,61.163628,7.733510,2.530601,0.0,4.280040,24.292221
2024-11-05 14:04:11+00:00,0.0,61.163526,7.733519,2.530604,0.0,4.280045,24.292306