In [1]:
from asset_allocation_over_time import _fetch_tvl_by_asset, ALL_AUTOPOOLS


destinations_df, token_value_df = _fetch_tvl_by_asset(ALL_AUTOPOOLS[0])

2025-05-04 13:43:41,430 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2025-05-04 13:43:41,431 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-05-04 13:43:41,622 INFO sqlalchemy.engine.Engine select current_schema()
2025-05-04 13:43:41,624 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-05-04 13:43:41,810 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2025-05-04 13:43:41,812 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-05-04 13:43:42,010 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-05-04 13:43:42,010 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-05-04 13:43:42,011 INFO sqlalchemy.engine.Engine [generated in 0.00113s] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x12c5d88b0>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-05-04 13:43:42,011 INFO sqlalchemy.engine.Engine SELECT
    tokens.symbol,
    tokens.token_address,
    token_values.safe_price,
    token_values.block,
    blocks.datetime
FROM tokens
JOIN token_values
  ON token_values.chain_id = tokens.chain_id AND token_values.token_address = tokens.token_address
JOIN blocks
  ON blocks.chain_id = token_values.chain_id AND blocks.block = token_values.block
WHERE
    (tokens.chain_id = 1)

2025-05-04 13:43:42,012 INFO sqlalchemy.engine.Engine [generated in 0.00039s] {}
2025-05-04 13:43:42,801 INFO sqlalchemy.engine.Engine ROLLBACK
2025-05-04 13:43:42,898 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-05-04 13:43:42,899 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-05-04 13:43:42,899 INFO sqlalchemy.engine.Engine [cached since 0.8896s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x12c5dbd90>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-05-04 13:43:42,900 INFO sqlalchemy.engine.Engine SELECT
    autopool_destination_states.owned_shares,
    autopool_destination_states.destination_vault_address,
    autopool_destination_states.block,
    destination_token_values.token_address,
    destination_token_values.quantity,
    destination_states.underlying_token_total_supply,
    destination_states.price_per_share,
    destinations.underlying_symbol
FROM autopool_destination_states
JOIN destination_token_values
  ON destination_token_values.chain_id = autopool_destination_states.chain_id AND destination_token_values.destination_vault_address = autopool_destination_states.destination_vault_address AND destination_token_values.block = autopool_destination_states.block
JOIN destination_states
  ON destination_states.chain_id = destination_token_values.chain_id AND destination_states.destination_vault_address = destination_token_values.destination_vault_address AND destination_states.block = destination_token_values.block
JOIN destinations
  ON destinations.chain_id = destination_token_values.chain_id AND destinations.destination_vault_address = destination_token_values.destination_vault_address
WHERE
    (autopool_destination_states.autopool_vault_address = '0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56' AND autopool_destination_states.owned_shares > 0)

2025-05-04 13:43:42,900 INFO sqlalchemy.engine.Engine [generated in 0.00060s] {}
2025-05-04 13:43:43,204 INFO sqlalchemy.engine.Engine ROLLBACK
2025-05-04 13:43:43,298 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-05-04 13:43:43,299 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-05-04 13:43:43,299 INFO sqlalchemy.engine.Engine [cached since 1.289s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x12c5d9b70>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-05-04 13:43:43,299 INFO sqlalchemy.engine.Engine SELECT
    tokens.symbol,
    tokens.token_address,
    token_values.safe_price,
    token_values.block,
    blocks.datetime
FROM tokens
JOIN token_values
  ON token_values.chain_id = tokens.chain_id AND token_values.token_address = tokens.token_address
JOIN blocks
  ON blocks.chain_id = token_values.chain_id AND blocks.block = token_values.block
WHERE
    (tokens.chain_id = 1)

2025-05-04 13:43:43,300 INFO sqlalchemy.engine.Engine [cached since 1.288s ago] {}
2025-05-04 13:43:43,515 INFO sqlalchemy.engine.Engine ROLLBACK
2025-05-04 13:43:43,612 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-05-04 13:43:43,613 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-05-04 13:43:43,613 INFO sqlalchemy.engine.Engine [cached since 1.604s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x12c5da5f0>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-05-04 13:43:43,614 INFO sqlalchemy.engine.Engine SELECT
    autopool_destination_states.owned_shares,
    autopool_destination_states.destination_vault_address,
    autopool_destination_states.block,
    destination_token_values.token_address,
    destination_token_values.quantity,
    destination_states.underlying_token_total_supply,
    destination_states.price_per_share,
    destinations.underlying_symbol
FROM autopool_destination_states
JOIN destination_token_values
  ON destination_token_values.chain_id = autopool_destination_states.chain_id AND destination_token_values.destination_vault_address = autopool_destination_states.destination_vault_address AND destination_token_values.block = autopool_destination_states.block
JOIN destination_states
  ON destination_states.chain_id = destination_token_values.chain_id AND destination_states.destination_vault_address = destination_token_values.destination_vault_address AND destination_states.block = destination_token_values.block
JOIN destinations
  ON destinations.chain_id = destination_token_values.chain_id AND destinations.destination_vault_address = destination_token_values.destination_vault_address
WHERE
    (autopool_destination_states.autopool_vault_address = '0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56' AND autopool_destination_states.owned_shares > 0)

2025-05-04 13:43:43,614 INFO sqlalchemy.engine.Engine [cached since 0.7143s ago] {}
2025-05-04 13:43:43,838 INFO sqlalchemy.engine.Engine ROLLBACK

In [18]:
import pandas as pd

df = pd.merge(destinations_df, token_value_df, on=["block", "token_address"])

df["portion_owned"] = (df["owned_shares"] / df["underlying_token_total_supply"]).fillna(1.0)
df["autopool_implied_safe_value"] = df["portion_owned"] * df["quantity"] * df["safe_price"]


pio.templates.default = None
import plotly.express as px

safe_value_by_destination = (
    df.groupby(["datetime", "underlying_symbol"])["autopool_implied_safe_value"]
    .sum()
    .reset_index()
    .pivot(columns=["underlying_symbol"], index=["datetime"], values="autopool_implied_safe_value")
)
safe_value_by_asset = (
    df.groupby(["datetime", "symbol"])["autopool_implied_safe_value"]
    .sum()
    .reset_index()
    .pivot(columns=["symbol"], index=["datetime"], values="autopool_implied_safe_value")
)
import plotly.io as pio

safe_value_by_destination

underlying_symbol,B-rETH-STABLE,ECLP-wstETH-cbETH,ECLP-wstETH-wETH,ETHx/wstETH,OETHCRV-f,autoETH,ethx-f,frxeth-ng-f,osETH-rETH,osETH/wETH-BPT,pxETH/wETH,pxethweth,pxsteth,wETHrETH,weETH/rETH,weeth-ng,wstETH-WETH-BPT
datetime,,,,,,,,,,,,,,,,,
2024-09-15 23:59:59+00:00,0.0,0.0,0.0,0.000000,0.000000,0.239949,0.000000,0.0,0.000000,0.0,0.000000e+00,0.000000,0.000000,0.0,0.000000e+00,0.000000,0.0
2024-09-16 23:59:59+00:00,0.0,0.0,0.0,0.000000,0.000000,944.081116,0.000000,0.0,0.000000,0.0,0.000000e+00,0.000000,0.000000,0.0,0.000000e+00,0.000000,0.0
2024-09-17 23:59:59+00:00,0.0,0.0,0.0,0.000000,0.000000,1554.391314,0.000000,0.0,0.000000,0.0,0.000000e+00,99.989238,0.000000,0.0,0.000000e+00,0.000000,0.0
2024-09-18 23:59:59+00:00,0.0,0.0,0.0,0.000000,0.000000,2572.961608,0.000000,0.0,0.000000,0.0,0.000000e+00,414.397542,146.016553,0.0,0.000000e+00,0.000000,0.0
2024-09-19 23:59:59+00:00,0.0,0.0,0.0,0.000000,0.000000,2471.666099,399.145710,0.0,0.000000,0.0,0.000000e+00,750.049556,280.653069,0.0,0.000000e+00,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-04-29 23:59:59+00:00,NaN,NaN,NaN,567.440854,NaN,179.975418,1716.037217,NaN,971.893253,NaN,1.435926e+14,3382.073062,5806.520454,NaN,2.339334e+14,1841.003111,NaN
2025-04-30 23:59:59+00:00,NaN,NaN,NaN,567.322516,89.161574,188.715846,1715.735655,NaN,1036.187098,NaN,1.435925e+14,3382.062823,5806.288375,NaN,2.320325e+14,1840.465289,NaN
2025-05-01 23:59:59+00:00,NaN,NaN,NaN,567.418776,153.069293,93.207835,1716.184934,NaN,1090.771892,NaN,1.492397e+14,3382.162516,5806.568200,NaN,2.147642e+14,1840.903771,NaN
2025-05-02 23:59:59+00:00,NaN,NaN,NaN,567.641174,287.443805,182.593540,1716.490230,NaN,1090.905961,NaN,1.492396e+14,3382.060263,5807.755902,NaN,2.147827e+14,1841.069008,NaN
2025-05-03 23:59:59+00:00,NaN,NaN,NaN,567.651388,390.506067,141.916823,1716.612542,NaN,1090.913177,NaN,1.376339e+14,3382.135129,5807.873618,NaN,2.147747e+14,1841.178340,NaN

In [22]:
underlying ='pxETH/wETH'

pxETH/weth quantity is wrong

bad_df = df[df['underlying_symbol'] ==underlying]
bad_df

,owned_shares,destination_vault_address,block,token_address,quantity,underlying_token_total_supply,price_per_share,underlying_symbol,symbol,safe_price,datetime,portion_owned,autopool_implied_safe_value
34,146.581002,0x8cA2201BC34780f14Bca452913ecAc8e9928d4cA,20852572,0x04C154b66CB340F3Ae24111CC767e0184Ed00Cc6,3.280676e+03,5076.084910,1.001557,pxETH/wETH,pxETH,0.998398,2024-09-28 23:59:59+00:00,0.028877,9.458365e+01
35,406.156197,0x8cA2201BC34780f14Bca452913ecAc8e9928d4cA,20859740,0x04C154b66CB340F3Ae24111CC767e0184Ed00Cc6,3.704710e+03,5732.513418,1.001635,pxETH/wETH,pxETH,0.998519,2024-09-29 23:59:59+00:00,0.070851,2.620949e+02
36,487.778070,0x8cA2201BC34780f14Bca452913ecAc8e9928d4cA,20866918,0x04C154b66CB340F3Ae24111CC767e0184Ed00Cc6,3.826636e+03,5921.233612,1.001621,pxETH/wETH,pxETH,0.998497,2024-09-30 23:59:59+00:00,0.082378,3.147559e+02
37,487.778070,0x8cA2201BC34780f14Bca452913ecAc8e9928d4cA,20874085,0x04C154b66CB340F3Ae24111CC767e0184Ed00Cc6,3.849045e+03,5955.914982,1.001629,pxETH/wETH,pxETH,0.998509,2024-10-01 23:59:59+00:00,0.081898,3.147593e+02
38,619.456081,0x8cA2201BC34780f14Bca452913ecAc8e9928d4cA,20881261,0x04C154b66CB340F3Ae24111CC767e0184Ed00Cc6,3.921067e+03,6087.597330,1.001640,pxETH/wETH,pxETH,0.998524,2024-10-02 23:59:59+00:00,0.101757,3.984075e+02
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1323,352.439573,0xc4Eb861e7b66f593482a3D7E8adc314f6eEDA30B,22392426,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,2.596148e+15,6130.977588,1.002393,pxETH/wETH,WETH,1.000000,2025-05-01 23:59:59+00:00,0.057485,1.492397e+14
3819,352.439573,0xc4Eb861e7b66f593482a3D7E8adc314f6eEDA30B,22399543,0x04C154b66CB340F3Ae24111CC767e0184Ed00Cc6,4.028659e+03,6130.984315,1.002363,pxETH/wETH,pxETH,0.998465,2025-05-02 23:59:59+00:00,0.057485,2.312318e+02
3820,352.439573,0xc4Eb861e7b66f593482a3D7E8adc314f6eEDA30B,22406692,0x04C154b66CB340F3Ae24111CC767e0184Ed00Cc6,4.020418e+03,6647.963736,1.002414,pxETH/wETH,pxETH,0.998500,2025-05-03 23:59:59+00:00,0.053015,2.128213e+02
3821,352.439573,0xc4Eb861e7b66f593482a3D7E8adc314f6eEDA30B,22399543,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,2.596148e+15,6130.984315,1.002363,pxETH/wETH,WETH,1.000000,2025-05-02 23:59:59+00:00,0.057485,1.492396e+14
3822,352.439573,0xc4Eb861e7b66f593482a3D7E8adc314f6eEDA30B,22406692,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,2.596148e+15,6647.963736,1.002414,pxETH/wETH,WETH,1.000000,2025-05-03 23:59:59+00:00,0.053015,1.376339e+14

In [ ]:
# weETH/rETH

In [14]:
safe_value_by_asset

                      datetime  symbol  autopool_implied_safe_value
0    2024-09-15 23:59:59+00:00    ETHx                 0.000000e+00
1    2024-09-15 23:59:59+00:00    OETH                 0.000000e+00
2    2024-09-15 23:59:59+00:00    WETH                 2.399486e-01
3    2024-09-15 23:59:59+00:00   cbETH                 0.000000e+00
4    2024-09-15 23:59:59+00:00  frxETH                 0.000000e+00
...                        ...     ...                          ...
1631 2025-05-03 23:59:59+00:00   pxETH                 5.700736e+03
1632 2025-05-03 23:59:59+00:00    rETH                 2.147747e+14
1633 2025-05-03 23:59:59+00:00   stETH                 2.447824e+03
1634 2025-05-03 23:59:59+00:00   weETH                 1.473690e+03
1635 2025-05-03 23:59:59+00:00  wstETH                 2.979603e+02

[1636 rows x 3 columns]

In [3]:
df

,owned_shares,destination_vault_address,block,token_address,quantity,underlying_token_total_supply,price_per_share,underlying_symbol,symbol,safe_price,datetime,portion_owned,implied_owned_value
0,224.593215,0xfB6f99FdF12E37Bfe3c4Cf81067faB10c465fb24,20838231,0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0,389.903175,826.996073,1.012281,ETHx/wstETH,wstETH,1.179669,2024-09-26 23:59:59+00:00,0.271577,124.913695
1,224.593215,0xfB6f99FdF12E37Bfe3c4Cf81067faB10c465fb24,20845405,0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0,298.248295,678.243214,1.012557,ETHx/wstETH,wstETH,1.179796,2024-09-27 23:59:59+00:00,0.331140,116.518860
2,224.593215,0xfB6f99FdF12E37Bfe3c4Cf81067faB10c465fb24,20852572,0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0,368.700311,802.152060,1.012263,ETHx/wstETH,wstETH,1.179689,2024-09-28 23:59:59+00:00,0.279988,121.781446
3,224.593215,0xfB6f99FdF12E37Bfe3c4Cf81067faB10c465fb24,20859740,0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0,322.695410,682.860669,1.012252,ETHx/wstETH,wstETH,1.179487,2024-09-29 23:59:59+00:00,0.328900,125.184452
4,224.593215,0xfB6f99FdF12E37Bfe3c4Cf81067faB10c465fb24,20866918,0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0,314.189788,682.931291,1.012420,ETHx/wstETH,wstETH,1.179794,2024-09-30 23:59:59+00:00,0.328866,121.904001
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3848,389.696195,0x3772973f8F399D74488D5cF3276C032E0afC8A6f,22406692,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,7074.961381,14891.393784,1.002078,OETHCRV-f,WETH,1.000000,2025-05-03 23:59:59+00:00,0.026169,185.146237
3849,286.856419,0x3772973f8F399D74488D5cF3276C032E0afC8A6f,22399543,0x856c4Efb76C1D1AE02e20CEB03A2A6a08b0b8dC3,7823.285423,14788.506076,1.002048,OETHCRV-f,OETH,0.999667,2025-05-02 23:59:59+00:00,0.019397,151.699769
3850,389.696195,0x3772973f8F399D74488D5cF3276C032E0afC8A6f,22406692,0x856c4Efb76C1D1AE02e20CEB03A2A6a08b0b8dC3,7849.560343,14891.393784,1.002078,OETHCRV-f,OETH,0.999722,2025-05-03 23:59:59+00:00,0.026169,205.359830
3851,182.593540,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,22399543,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,182.593540,NaN,1.000000,autoETH,WETH,1.000000,2025-05-02 23:59:59+00:00,1.000000,182.593540
3852,141.916823,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,22406692,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,141.916823,NaN,1.000000,autoETH,WETH,1.000000,2025-05-03 23:59:59+00:00,1.000000,141.916823

In [4]:
df.loc["underlying_token_total_supply", df["underlying_token_total_supply"].isna()]
# undelryign total supply = None, for the autopool itself

KeyError: 'underlying_token_total_supply'

In [ ]:
destinations_df

,owned_shares,destination_vault_address,block,token_address,quantity,underlying_token_total_supply,price_per_share
0,0.000000,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,20759464,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,7077.280862,13157.451200,1.036523
1,0.000000,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,20766617,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,7091.767922,13157.496413,1.036163
2,0.000000,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,20773761,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,7042.071304,13157.496413,1.036462
3,0.000000,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,20780916,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,7145.366574,13268.458946,1.036491
4,0.000000,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,20788084,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,7069.241070,13268.526874,1.036501
...,...,...,...,...,...,...,...
13544,389.696195,0x3772973f8F399D74488D5cF3276C032E0afC8A6f,22406692,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,7074.961381,14891.393784,1.002078
13545,286.856419,0x3772973f8F399D74488D5cF3276C032E0afC8A6f,22399543,0x856c4Efb76C1D1AE02e20CEB03A2A6a08b0b8dC3,7823.285423,14788.506076,1.002048
13546,389.696195,0x3772973f8F399D74488D5cF3276C032E0afC8A6f,22406692,0x856c4Efb76C1D1AE02e20CEB03A2A6a08b0b8dC3,7849.560343,14891.393784,1.002078
13547,182.593540,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,22399543,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,182.593540,NaN,1.000000
13548,141.916823,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,22406692,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,141.916823,NaN,1.000000