In [41]:



# we move from Idle to a destination, expecting it to yeild 10% at t=0
# follow up at t= 7, 30, ect with the gross return. of that destination

# nav in destination, lp tokens owned. 

# nav per lp token

# also compare that to the other destinations. 
from mainnet_launch.pages.solver_diagnostics.solver_diagnostics import _load_solver_df, AUTO_ETH
from mainnet_launch.pages.rebalance_events.rebalance_events import fetch_rebalance_events_df
import pandas as pd

solver_df = _load_solver_df(AUTO_ETH)
rebalnace_df = fetch_rebalance_events_df(AUTO_ETH)
rebalnace_df

2025-02-07 16:02:11.969 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-07 16:02:11.970 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-07 16:02:11.971 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-07 16:02:12.140 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-07 16:02:12.140 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

                                                  event  ... actual_swap_cost
timestamp                                                ...
2024-10-05 19:31:23+00:00               RebalanceToIdle  ...        -0.265843
2024-10-20 10:31:35+00:00               RebalanceToIdle  ...         0.066231
2024-10-23 22:31:23+00:00               RebalanceToIdle  ...         0.060810
2024-11-21 07:31:11+00:00               RebalanceToIdle  ...         0.092897
2024-11-26 16:31:11+00:00               RebalanceToIdle  ...         0.032066
...                                                 ...  ...              ...
2024-10-13 21:56:35+00:00  RebalanceBetweenDestinations  ...              NaN
2024-10-14 21:40:23+00:00  RebalanceBetweenDestinations  ...              NaN
2025-02-05 07:32:35+00:00  RebalanceBetweenDestinations  ...        -0.040949
2025-02-05 22:31:35+00:00  RebalanceBetweenDestinations  ...        -0.062156
2025-02-06 13:31:23+00:00  RebalanceBetweenDestinations  ...         0.018237

[248 rows x 22 columns]

In [37]:
rebalnace_df.sort_index()[:-50].tail(10)

                                                  event  ... actual_swap_cost
timestamp                                                ...
2025-01-02 22:31:23+00:00  RebalanceBetweenDestinations  ...         0.085113
2025-01-03 13:31:23+00:00  RebalanceBetweenDestinations  ...         0.095856
2025-01-04 04:31:23+00:00  RebalanceBetweenDestinations  ...         0.062901
2025-01-04 19:31:11+00:00  RebalanceBetweenDestinations  ...         0.009943
2025-01-05 10:31:11+00:00  RebalanceBetweenDestinations  ...         0.015279
2025-01-06 01:31:23+00:00  RebalanceBetweenDestinations  ...         0.067477
2025-01-06 16:31:11+00:00  RebalanceBetweenDestinations  ...         0.012210
2025-01-07 07:31:11+00:00  RebalanceBetweenDestinations  ...         0.065087
2025-01-07 22:31:23+00:00  RebalanceBetweenDestinations  ...         0.016893
2025-01-08 07:31:11+00:00  RebalanceBetweenDestinations  ...         0.156220

[10 rows x 22 columns]

In [40]:
my_rebalance = rebalnace_df[rebalnace_df['block'] == 21539789].T
my_rebalance

timestamp                                                               2025-01-02 22:31:23+00:00
event                                                                RebalanceBetweenDestinations
hash                                            0x804b15b5749314ab25b443c1c6471d796ef2acd75586...
block                                                                                    21539789
outEthValue                                                                                 100.0
inEthValue                                                                              99.914887
moveName                                                     autoETH (tokemak) -> pxsteth (curve)
gasCostInETH                                                                             0.034633
out_compositeReturn                                                                           0.0
in_compositeReturn                                                                       8.261539
predicted_gain_during_swap_cost_off_set_period                                           1.040294
swapCost                                                                                 0.085113
slippage                                                                                 0.000851
break_even_days                                                                          3.763561
offset_period                                                                                46.0
solver_profit                                                                               0.015
predicted_increase_after_swap_cost                                                       0.955181
outDestinationVault                                    0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56
inDestinationVault                                     0xe4433D00Cf48BFE0C672d9949F2cd2c008bffC04
autopool                                                                                  autoETH
gas_price                                                                             11015433127
gas_used                                                                                  3144039
actual_swap_cost                                                                         0.085113

In [56]:
limited_df = solver_df[solver_df['moveName'] == 'autoETH (tokemak) -> pxsteth (curve)'].copy()
my_solver = limited_df[limited_df['minAmountInETH'] == '99954818294404382720']
my_solver.T

                                                               89
timestamp                                              1735857021
sodOnly                                                     False
chainId                                                         1
solverAddress          0x952D7a7eB2e0804d37d9244BE8e47341356d2f5D
poolAddress            0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56
destinationOut                                  autoETH (tokemak)
tokenOut               0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
amountOut                                   100000000000000000000
amountOutETH                                100000000000000000000
destinationIn                                     pxsteth (curve)
tokenIn                0x6951bDC4734b9f7F3E1B74afeBC670c736A0EDB6
minAmountIn                                  98748943074852782080
minAmountInETH                               99954818294404382720
steps           [{'stepType': 'swap', 'dex': '0xV2', 'tokenOut...
sod             {'currentTimestamp': 1735857021, 'destStates':...
rebalanceTest   {'currentTimestamp': 1735857021, 'type': 'From...
addRank         [[Tokemak-Wrapped Ether-pxETH/stETH, 9.4559631...
date                                    2025-01-02 22:30:21+00:00
moveName                     autoETH (tokemak) -> pxsteth (curve)

In [ ]:
# today I am working on comparing what we thought the composite return of a
#  destination was and how much that destination grew over the next month/week

In [ ]:
# destination vault, 
# nav/lp tokens.
# eth earned. by selling the rewards claimed and the rewards earned.